# About the author {#sec-about-the-author .unnumbered .unlisted}

I am a Reader[^00_about_the_author-1] at the University of Warwick. My research interfaces with multiple disciplines, such as International Management, Organisational Behaviour, Cross-cultural Psychology and Intercultural Communication. Most of my research investigates real-life issues in organisational contexts using a diagnostic angle with an emphasis to help improve organisational members' experiences and organisational performance.

[^00_about_the_author-1]: A Reader is a senior academic position, a rank between Associate Professor and Full Professor.

For more than 15 years, I have enjoyd teaching students how to turn data into meaningful recommendations for businesses, universities and the broader society by conveying relevant theory-driven knowledge as well as research methods skills. In addition, I am enthusiastic about new approaches to analysing data, whether it is quantitative or qualitative.

My most recent publications can be found on [ResearchGate](https://www.researchgate.net/profile/Daniel-Dauber "ResearchGate Profile: Daniel Dauber"){target="_blank"}, and I regularly post tutorials about R, productivity and other hidden gems of academic life on my blog: [The Social Science Sofa](https://www.thesocialsciencesofa.com "Website: The Social Science Sofa"){target="_blank"}. If you like to connect with me, you can find me on [X/Twitter](https://twitter.com/daniel_dauber "Twitter profile: Daniel Dauber"){target="_blank"}.
