# Case studies {#sec-case-studies}

In this section of the book, we work through analytical techniques covered in this book. However, this time, I will walk you through the entire process of wrangling, exploring, visualising, and statistically enquiring about our dataset. After having worked through the whole book, you might be wondering how, in practice, all these puzzle pieces fit together in specific scenarios. This is what this chapter offers. It also reveals some of my workflows when working with quantitative data and how I tackle challenging issues with data. Lastly, the following case studies also summarise learned concepts in R. Let's jump right in. 


## Bootstrapped regression with multi-level control variable and moderation {#sec-case-study-bootstrapped-regression}

```{r}
# # Bootstrapping the regression
#
# parameters::compare_parameters(m1, m2) |>
#   as_tibble() |>
#   select(Parameter, Coefficient.m1, Coefficient.m2)
#
# # create bootstrapped samples
# set.seed(1234)
# boot_sample <- rsample::bootstraps(m1_outliers,
#                                            times = 500)
#
# # Run lm with bootstrapped samples
#
# split <- function(split) {
#   lm(lm(new_cases ~ masks + movements + gatherings + schools + businesses + travel,
#         data = rsample::analysis(split)))
# }
#
# mb <- boot_sample |>
#   mutate(lm_mod = map(splits, split),
#          estimates = map(lm_mod, broom::tidy))
#
# model_sum <-
#   mb |>
#   unnest(estimates) |>
#   filter(term != "(Intercept)") |>
#   group_by(term) |>
#   mutate(estimate = scale(estimate)) |>
#   ungroup()
#
#
# model_sum |>
#   ggplot(aes(x = estimate,
#              y = term,
#              fill = term)) +
#   ggridges::geom_density_ridges()
#
# #check for multicollinearity
#
# ## Durbin-Watson Test
# car::durbinWatsonTest()
```
