project:
  type: book

book:
  title: "R for Non-Programmers: A Guide for Social Scientists"
  output-file: "r4np-crc"
  author: "Daniel Dauber"
  date: "last-modified"
  favicon: r4np_icon.png
  description: "Are you interested in learning R, but intimidated by programming and statistical analysis? 'R for Non-Programmers: A Guide for Social Scientists' is the perfect resource for you. This book provides practical and efficient solutions to common challenges in empirical research in the Social Sciences, without assuming any prior knowledge or skills in programming or statistical analysis. Each chapter is dedicated to a specific task required to answer research questions and includes exercises and case studies based on real data. Whether you are a novice or experienced analyst, this book is a comprehensive entry to R programming that will help enhance your data analysis skills."
  repo-url: https://github.com/ddauber/r4np-quarto-crc
  repo-actions: [source, issue]
  
  chapters:
    - index.qmd
    - 00_about_the_author.qmd
    - 00_acknowledgements.qmd
    - 01_before_you_get_started.qmd
    - 02_why_start_learning_a_programming_language.qmd
    - 03_setting_up_r_rstudio.qmd
    - 04_rstudio_interface.qmd
    - 05_r_basics.qmd
    - 06_starting_r_projects.qmd
    - 07_data_wrangling.qmd
    - 08_descriptive_statistics.qmd
    - 09_sources_of_bias.qmd
    - 10_correlations.qmd
    - 11_group_comparison.qmd
    - 12_power_analysis.qmd
    - 13_regressions.qmd
    - 14_mixed_methods.qmd
    - 15_next_steps.qmd
    - 18_epilogue.qmd
    - 99_appendix.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - r4np.scss
    include-in-header:
      - _ga.html
      - header.html
      
  # pdf:
  #   documentclass: krantz
  #   keep-tex: true
  #   include-in-header: latex/preamble.tex
  #   include-before-body: latex/before_body.tex
  #   include-after-body: latex/after_body.tex
