project:
  type: book

book:
  title: "Our name"
  output-file: "eds-crc"
  author: "Zobitz and Zimmerman"
  date: "12/02/2024"

  chapters:
    - index.qmd
    - 02_data_for_env_science.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: krantz
    keep-tex: true
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
