{
  "hash": "9e3c5d1c2016d5b00ab3d073515f11ac",
  "result": {
    "engine": "knitr",
    "markdown": "# Regression: Creating models to predict future observations {#sec-regression}\n\n\n\n\n\nRegressions are an exciting area of data analysis since it enables us to make very specific predictions, incorporating different variables simultaneously. As the name implies, regressions 'regress', i.e., draw on past observations to make predictions about future observations. Thus, any analysis incorporating a regression makes the implicit assumption that the past best explains the future.\n\nI once heard someone refer to regressions as driving a car by looking at the rear-view mirror. As long as the road is straight, we will be able to navigate the car successfully. However, if there is a sudden turn, we might drive into the abyss. This makes it very clear when and how regressions can be helpful. Regressions are also a machine learning method, which falls under *models with supervised learning*. If you find machine learning fascinating, you might find the book *\"Hands-on Machine Learning with R\"* [@boehmke2019hands] very insightful and engaging.\n\nIn the following chapters, we will cover three common types of regressions, which are also known as *Ordinary Least Squares (OLS) regression* models:\n\n-   Single linear regression,\n\n-   Multiple regression, and\n\n-   Hierarchical regression, as a special type of multiple regression.\n\nThese three types will allow you to perform any OLS regression you could imagine. We can further distinguish two approaches to modelling via regressions:\n\n-   *Hypothesis testing*: A regression model is defined ex-ante.\n\n-   *Machine learning*: A model is developed based on empirical data.\n\nIn the following chapters, we will slightly blur the lines between both approaches by making assumptions about relationships (hypothesising) and make informed decisions based on our data (exploring).\n\nAll our regressions will be performed using the `covid` dataset of the `r4np` package to investigate whether certain factors can predict COVID numbers in different countries. I felt this book would not have been complete without covering this topic. After all, I wrote this piece during the pandemic, and it likely will mark a darker chapter in human history.\n\n## Single linear regression {#sec-single-linear-regression}\n\nA single linear regression looks very similar to a correlation (see @sec-correlations), but it is different in that it defines which variable affects another variable, i.e. a directed relationship. I used the terms *dependent variable (DV)* and *independent variable (IV)* previously when comparing groups (see @sec-comparing-groups), and we will use them here again. In group comparisons, the independent variable was usually a `factor`, but in regressions, we can use data that is not a categorical variable, i.e. `integer`, `double`, etc.\n\nWhile I understand that mathematical equations can be confusing, they are fairly simple to understand with regressions. Also, when writing our models in *R*, we will continuously use a `formula` to specify our regression. Thus, it is advisable to understand them. For example, a single linear regression consists of one independent variable and one dependent variable:\n\n::: {align=\"center\"}\n$$\nDV = \\beta_{0} + IV * \\beta_{1} + error\n$$\n:::\n\nBeta ($\\beta$) represents the coefficient of the independent variable, i.e. how much a change in IV causes a change in DV. For example, a one-unit change in IV might mean that DV changes by two units of IV:\n\n::: {#single-linear-regression-example align=\"center\"}\n$$\nDV = \\beta_0 + IV * 2 + error\n$$\n:::\n\nIf we ignore $\\beta_0$ and $error$ for a moment, we find that that if $IV = 3$, our $DV = 3*2 = 6$. Similarly, if $IV = 5$, we find that $DV = 10$, and so on. According to this model, DV will always be twice as large as IV.\n\nYou might be wondering what $\\beta_0$ stands for. It indicates an offset for each value, also called the intercept. Thus, no matter which value we choose for IV, DV will always be $\\beta_0$ different from IV. It is a constant in our model. This can be best explained by visualising a regression line. Pay particular attention to the expressions after `\\(x)`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A: Two models with different beta(0)\nggplot() +\n  geom_function(fun = \\(x) 0 + x * 2, col = \"red\") +\n  geom_function(fun = \\(x) 1 + x * 2, col = \"blue\") +\n  see::theme_modern()  \n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/beta-zero-beta-one-explained-1.png){fig-alt='A plot with two diagonal lines that run in parallel. The blue line represents a beta zero of 1, while the red line represents a regression line with beta zero of 0.' width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# B: Two models with the same beta(0), but different beta(1)\nggplot() +\n  geom_function(fun = \\(x) 0 + x * 2, col = \"red\") +\n  geom_function(fun = \\(x) 0 + x * 3, col = \"blue\") +\n  see::theme_modern()\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/beta-zero-beta-one-explained-diff-1.png){fig-alt='A plot with a red and blue regression line. Both lines have a shared origin at zero, but have different steepness.' width=672}\n:::\n:::\n\n\nPlot A shows two regressions where only $\\beta_0$ differs, i.e. the intercept. On the other hand, plot B shows what happens if we change $\\beta_1$, i.e. the slope. The two models in plot B have the same intercept and, therefore, the same origin. However, the blue line ascends quicker than the red one because its $\\beta_1$ is higher than for the red model.\n\nLastly, the $error$ component in the regression model refers to the deviation of data from these regression lines. Ideally, we want this value to be as small as possible.\n\n### Fitting a regression model by hand, i.e. trial and error {#sec-fitting-a-regression-model-by-hand}\n\nIf everything so far sounds all awfully theoretical, let's try to fit a regression model by hand. First, we need to consider what our model should be able to predict. Let's say that the number of COVID-19 cases predicts the number of deaths due to COVID-19. Intuitively we would assume this should be a linear relationship because the more cases there are, the more likely we find more deaths caused by it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We only select most recent numbers, i.e. \"2021-08-26\"\n# and countries which have COVID cases\ncovid_sample <-\n  covid |>\n  filter(date_reported == \"2021-08-26\" &\n         cumulative_cases != 0)\n\ncovid_sample |>\n  ggplot(aes(x = cumulative_cases,\n             y = cumulative_deaths)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/fitting-model-by-hand-step-one-1.png){fig-alt='This scatter plot displays the relationship between ‘cumulative_cases’ and ‘cumulative_deaths’. Each point represents a data entry, showing that as cumulative cases increase, cumulative deaths tend to increase as well, indicating a positive association between these two variables. However, observations are clustered together in the bottom right-hand corner.' width=672}\n:::\n:::\n\n\nThis data visualisation does not show us much. For example, we can see three countries, which appear to have considerably more cases than most other countries. Thus, all other countries are crammed together in the bottom left corner. To improve this visualisation without removing the outliers, we can rescale the x- and y-axis using the function `scale_x_continuous()` and `scale_y_continuous()` and apply a `\"log\"` transformation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_sample |>\n  ggplot(aes(x = cumulative_cases,\n             y = cumulative_deaths)) +\n  geom_point() +\n  scale_x_continuous(trans = \"log\") +\n  scale_y_continuous(trans = \"log\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/fitting-model-by-hand-step-two-1.png){fig-alt='This scatter plot illustrates the positive correlation between ‘cumulative_cases’ and ‘cumulative_deaths’. As cumulative cases increase, cumulative deaths tend to rise, with a strong upward trend suggesting a proportional relationship between these two variables.' width=672}\n:::\n:::\n\n\nAs a result, the scatterplot is now easier to read, and the dots are more spread out. This reveals that there is quite a strong relationship between `cumulative_cases` and `cumulative_deaths`. However, similar to before, we should avoid outliers when performing our analysis. For the sake of simplicity, I will limit the number of countries included in our analysis, which also removes the requirement of using `scale_x_continuous()` and `scale_y_continuous()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_sample <-\n  covid_sample |>\n  \n  # Filter observations based on multiple criteria\n  filter(date_reported == \"2021-08-26\" &\n           cumulative_cases >= 2500 &\n           cumulative_cases <= 150000 &\n           cumulative_deaths <= 3000)\n\nplot <- covid_sample |>\n  ggplot(aes(x = cumulative_cases,\n             y = cumulative_deaths)) +\n  geom_point()\n\nplot\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/fitting-model-by hand-step-three-1.png){fig-alt='This scatter plot shows the relationship between ‘cumulative_cases’ and ‘cumulative_deaths’. The points suggest a general upward trend, indicating that as cumulative cases increase, cumulative deaths also tend to rise, although with some variability among the data points.' width=672}\n:::\n:::\n\n\nWe can try to fit a straight line on top by adjusting the beta values through trial and error. This is effectively what we hope to achieve with a regression: the $\\beta$ values, which best explain our data. Let's start with the basic assumption of $y = x$ without specific $\\beta$s, i.e. they are `0`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot +\n  geom_function(fun = \\(x) x, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/fitting-model-by-hand-step-four-1.png){fig-alt='This scatter plot displays ‘cumulative_cases’ on the x-axis and ‘cumulative_deaths’ on the y-axis, with a red regression line indicating the trend between the two variables. The line suggests a positive association, but all observations fall below this line indicating a poor fit.' width=672}\n:::\n:::\n\n\nWhat we try to achieve is that the red line fits nicely inside the cloud of dots. Our simple model provides a very poor fit to our data points, because the dots are considerably below it. This makes sense because $y = x$ would imply that every COVID-19 case leads to a death, i.e. everyone with COVID did not survive. From our own experience, we know that this is luckily not true. Ideally, we want the line to be less steep. We can do this by adding a $\\beta_1$ to our equation. Maybe only 2% of people who got COVID-19 might not have recovered, i.e. $\\beta_1 = 0.02$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot +\n  geom_function(fun = \\(x) 0.02 * x, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/fitting-model-by-hand-step-five-1.png){fig-alt='This scatter plot displays ‘cumulative_cases’ on the x-axis and ‘cumulative_deaths’ on the y-axis, with a red regression line indicating the trend between the two variables. The line suggests a positive association, and this time all observations fall roughly on this line indicating a better fit.' width=672}\n:::\n:::\n\n\nThis time the line looks much more aligned with our observations. However, one could argue that it might have to move a little to the right to cover the observations at the bottom better. Therefore, we should add a $\\beta_0$ to our equation, e.g. `-50`. This moves the line to the right. I also adjusted $\\beta_1$ ever so slightly to make it fit even better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot +\n  geom_function(fun = \\(x) -50 + 0.015 * x, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/fitting-model-by-hand-step-six-1.png){fig-alt='This scatter plot is similar to the previous one, but with minor adjustments to fit the red line onto the black dots even better.' width=672}\n:::\n:::\n\n\nWe finished creating our regression model. If we wanted to express it as a formula, we would write $DV = -5 + 0.015 * IV$. We could use this model to predict how high COVID cases will likely be in other countries not included in our dataset.\n\n### Fitting a regression model computationally {#sec-fitting-a-regression-model-computationally}\n\nEstimating a regression model by hand is not ideal and far from accurate. Instead, we would compute the $\\beta$s based on our observed data, i.e. `cumulative_cases` and `cumulative_deaths`. We can use the function `lm()` to achieve this. I also rounded (`round()`) all `numeric` values to two decimal places to make the output easier to read. We also use `tidy()` to retrieve a cleaner result from the computation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We define our model\nm0 <- lm(cumulative_deaths ~ cumulative_cases, data = covid_sample)\n\n# We clean the output to make it easer to read\n# This is optional\n\nbroom::tidy(m0) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term             estimate std.error statistic p.value\n  <chr>               <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)         88.1       70.5      1.25    0.21\n2 cumulative_cases     0.01       0       10.7     0   \n```\n\n\n:::\n:::\n\n\nWe first might notice that the `p.value` indicates that the relationship between `cumulative death` and `cumulative_cases` is significant. Thus, we can conclude that countries with more COVID cases also suffer from higher numbers of people who do not recover successfully from it. However, you might be wondering where our $\\beta$ scores are. They are found where it says `estimate`. The standard error (`std.error`) denotes the `error` we specified in the [previous equation](#single-linear-regression). In the first row, we get the $\\beta_0$, i.e. the intercept (88.10). This one is larger than what we estimated, i.e. `-50`. However, $\\beta_1$ is 0.01, which means we have done a very good job guessing this estimate. Still, it becomes apparent that it is much easier to use the function `lm()` to estimate a model than eyeballing it.\n\nReturning to our data, we can now visualise the computed model (in blue) and our guessed model (in red) in one plot and see the differences. The plot shows that both regression lines are fairly close to each other. Admittedly, it was relatively easy to fit this model by hand. However, it is much more difficult to do so when more than two variables are involved.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot +\n  geom_function(fun = \\(x) -50 + 0.015 * x, col = \"red\") +\n    geom_function(fun = \\(x) 88.1 + 0.01 * x, col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/comparing-computed-vs-hand-fitted-1.png){fig-alt='This scatter plot shows ‘cumulative_cases’ on the x-axis and ‘cumulative_deaths’ on the y-axis, with two competing regression lines. The red line represents a manually fitted regression, while the blue line represents a computed regression line based on the data points. The slight divergence between the two lines suggests differences in accuracy. The red line is a less optimal fit.' width=672}\n:::\n:::\n\n\nWith our final model computed, we also need to check its quality in terms of predictive power based on how well it can explain our observed data. We tested models before when we looked at confirmatory factor analyses for latent variables (see @sec-latent-constructs). This time we want to know how accurate our model is in explaining observed data and, therefore, how accurate it predicts future observations. The package `performance` offers a nice shortcut to compute many different indicators at once:\n\n-   `check_model()`: Checks for linearity, homogeneity, collinearity and outliers\n\n-   `model_performance()`: Tests the quality of our model.\n\nFor now, we are mainly interested in the performance of our model. So, we can obtain this information the following way:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::model_performance(m0) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1\nColumns: 7\n$ AIC         <dbl> 1472.626\n$ AICc        <dbl> 1472.887\n$ BIC         <dbl> 1480.319\n$ R2          <dbl> 0.5479547\n$ R2_adjusted <dbl> 0.5431457\n$ RMSE        <dbl> 502.5726\n$ Sigma       <dbl> 507.891\n```\n\n\n:::\n:::\n\n\nWe are presented with quite a number of performance indicators, and here is how to read them:\n\n-   `AIC` stands for *Akaike Information Criterion,* and the lower the score, the better the model.\n\n-   `BIC` stands for *Bayesian Information Criterion,* and the lower the score, the better the model.\n\n-   `R2` stands for *R squared* ($R^2$) and is also known as the coefficient of determination. It measures how much the independent variable can explain the variance in the dependent variable. In other words, the higher $R^2$, the better is our model, because our model can explain more of the variance. $R^2$ falls between 0-1, where 1 would imply that our model can explain 100% of the variance in our sample. $R^2$ is also considered a *goodness-of-fit measure*.\n\n-   `R2 (adj.)` stands for *adjusted R squared*. The adjusted version of $R^2$ becomes essential if we have more than one predictor (i.e. multiple independent variables) in our regression. The adjustment of $R^2$ accounts for the number of independent variables in our model. Thus, we can compare different models, even though they might have different numbers of predictors. It is important to note that the unadjusted $R^2$ will always increase if we add more predictors.\n\n-   `RMSE` stands for *Root Mean Square Error* and indicates how small or large the prediction error of the model is. Conceptually, it aims to measure the average deviations of values from our model when we attempt predictions. The lower its score, the better, i.e. a score of 0 would imply that our model perfectly fits the data, which is likely never the case in the field of Social Sciences. The *RMSE* is particularly useful when trying to compare models.\n\n-   `Sigma` stands for the standard deviation of our residuals (the difference between predicted and empirically observed values) and is a measure of prediction accuracy. `Sigma` is *'a measure of the average distance each observation falls from its prediction from the model'* [@gelman2020regression] (p. 168).\n\nMany of these indices will become more relevant when we compare models. However, $R^2$ can also be meaningfully interpreted without a reference model. We know that the bigger $R^2$, the better. In our case, it is `0.548`, which is very good considering that our model consists of only one predictor. It is not easy to interpret whether a particular $R^2$ value is good or bad. In our simple single linear regression, $R^2$ is literally *'r squared'*, which we already know from correlations and their effect sizes (see @tbl-effect-size-cohen). Thus, if we take the square root of $R^2$ we can retrieve the correlation coefficient, i.e. $r = \\sqrt{R^2} = \\sqrt{0.548} = 0.740$. According to @cohen1988statistical, this would count as a large effect size.\n\nHowever, the situation is slightly more complicated for multiple regressions, and we cannot use Cohen's reference table by taking the square root of $R^2$. Still, the meaning of $R^2$ and its adjusted version remain the same for our model.\n\nOnce you have a model and it is reasonably accurate, you can start making predictions. This can be achieved by using our model object `m0` with the function `add_predictions()` from the `modelr` package. However, first, we should define a set of values for our independent variable, i.e. `cumulative_cases`, which we store in a tibble using the `tibble()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A dataset with values for cumulative cases of COVID\ndf_predict <-\n  tibble(cumulative_cases = c(100, 1000, 10000))\n\n# Make our predictions\ndf_predict |>\n  modelr::add_predictions(m0) |>\n  mutate(pred = round(pred, 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  cumulative_cases  pred\n             <dbl> <dbl>\n1              100    90\n2             1000   102\n3            10000   232\n```\n\n\n:::\n:::\n\n\nThe predictions are stored in column `pred`. Therefore, we know how many deaths from COVID have to be expected based on our model for each value in our dataset.\n\nSingle linear regressions are simple and an excellent way to introduce novice users of *R* to modelling social phenomena. However, we hardly ever find that a single variable can explain enough variance to be a helpful model. Instead, we can most likely improve most of our single regression models by considering more variables and using a multiple regression technique.\n\n## Multiple regression {#sec-multiple-regression}\n\nMultiple regressions expand single linear regressions by allowing us to add more variables. Maybe less surprising, computing a multiple regression is similar to a single regression in *R* because it requires the same function, i.e. `lm()`. However, we add more IVs. Therefore, the equation we used before needs to be modified slightly by adding more independent variables. Each of these variables will have its own $\\beta$ value:\n\n::: {align=\"center\"}\n$$\nDV = \\beta_{0} + IV_{1} * \\beta_{1} + IV_{2} * \\beta_{2} + ... + IV_{n} * \\beta_{n} + error\n$$\n:::\n\nIn the last section, we wanted to know how many people will likely not recover from COVID. However, it might be even more interesting to understand how we can predict new cases and prevent casualties from the outset. Since I live in the United Kingdom during the pandemic, I am curious whether specific COVID measures help reduce the number of new cases in this country. To keep it more interesting, I will also add Germany to the mix since it has shown to be very effective in handling the pandemic relative to other European countries. Of course, feel free to pick different countries (maybe the one you live in?) to follow along with my example. In @sec-moderated-regression it will become apparent why I chose two countries (#spoiler-alert).\n\nFirst, we create a dataset that only contains information from the `United Kingdom` and `Germany`[^13_regressions-1], using `filter()`.\n\n[^13_regressions-1]: Germany is called 'Deutschland' in German, hence the abbreviation 'DEU' according to the [ISO country code](https://www.iso.org/obp/ui/#iso:code:3166:DE \"ISO country code\"){target=\"blank\"}.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_uk_ger <-\n  covid |>\n  filter(iso3 == \"GBR\" | iso3 == \"DEU\")\n```\n:::\n\n\nIn the next step, we might want to know how new cases are distributed over time. It is always good to inspect the dependent variable to get a feeling of how much variance there is in our data. Having a more extensive range of data values is ideal because the regression model will consider low and high values of the dependent variable instead of just high or low scores. If you find that your dependent variable shows minimal variance, your model will likely be *'overfitted'*. An overfitted model can very well explain the sample data but performs poorly with a new dataset. This is, of course not desirable, because the value of creating a model is to predict future observations. Let's plot the DV `new_cases` across time to see when and how many new COVID cases had to be reported for both countries together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_uk_ger |>\n  ggplot(aes(x = date_reported,\n             y = new_cases)) +\n  geom_col()\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/mr-plot-new-cases-1.png){width=672}\n:::\n:::\n\n\nWe can tell that there are different waves of new cases with very low and very high values. As such, we should find variables that help us explain when `new_cases` are high and when they are low. If you have hypotheses to test, you would already know which variables to include in your regression. However, we do not have a hypothesis based on our prior reading or other studies. Thus, we pick variables of interest that we suspect could help us with modelling new COVID cases. For example, we can be fairly confident that the number of new COVID cases should be lower if more safety measures are in place - assuming that they are effective and everyone adheres to them. The `covid` dataset includes such information evaluated by the [WHO](https://covid19.who.int/info/ \"WHO\"){target=\"blank\"}, i.e. `masks`, `travel`, `gatherings`, `schools` and `movements`. Remember, you can always find out what these variables stand for by typing `?covid` into the console. A higher value for these variables indicates that there were more safety measures in place. Scores can range from `0` (i.e. no measures are in place) to `100` (i.e. all WHO measures are in place).\n\nWe can add multiple variables by using the `+` symbol in the `lm()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create our model\nm0 <- lm(new_cases ~ masks + movements + gatherings +\n           schools + businesses + travel,\n         data = covid_uk_ger)\n\n# Inspect the model specifications.\n# I always round the p.value since I\n# do not prefer the scientific notation\nbroom::tidy(m0) |>\n  mutate(p.value = round(p.value, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)  -2585.     745.       -3.47   0.001\n2 masks          -14.8      9.18     -1.61   0.108\n3 movements      -54.7     15.5      -3.52   0    \n4 gatherings     -26.0     19.8      -1.31   0.191\n5 schools        394.      29.7      13.2    0    \n6 businesses      93.7     13.8       6.79   0    \n7 travel          49.5      9.30      5.32   0    \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Evaluate the quality of our model\nperformance::model_performance(m0) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1\nColumns: 7\n$ AIC         <dbl> 25277.62\n$ AICc        <dbl> 25277.74\n$ BIC         <dbl> 25318.26\n$ R2          <dbl> 0.2332214\n$ R2_adjusted <dbl> 0.2293258\n$ RMSE        <dbl> 10027.2\n$ Sigma       <dbl> 10056.88\n```\n\n\n:::\n:::\n\n\nOverall (and purely subjectively judged), the model is not particularly great because even though we added so many variables, the $adjusted \\ R^2$ is not particularly high, i.e. 'only' `0.229`. As mentioned earlier, for multiple regression, it is better to look at $adjusted \\ R^2$, because it adjusts for the number of variables in our model and makes the comparison of different models easier. There are a couple more important insights gained from this analysis:\n\n-   Not all variables appear to be significant. The predictors `masks` and `gatherings` are not significant, i.e. `p.value > 0.05`. Thus, it might be worth removing these variables to optimise the model.\n\n-   The variable, `movements` seems to reduce `new_cases`, i.e. it has a negative estimate ($\\beta$).\n\n-   However, `schools`, `businesses`, and `travel` have a positive effect on `new_cases`.\n\nEspecially the last point might appear confusing. How can it be that if more measures are taken, the number of new COVID cases increases? Should we avoid them? We have not considered in our regression that measures might be put in place to reduce the number of new cases rather than to prevent them. Thus, it might not be the case that `schools`, `businesses`, and `travel` predict higher `new_cases`, but rather the opposite, i.e. due to higher `new_cases`, the measures for `schools`, `businesses` and `travel` were tightened, which later on (with a time lag) led to lower `new_cases`. Thus, the relationships might be a bit more complicated, but to keep things simple, we accept that with our data, we face certain limitations (as is usually the case)[^13_regressions-2].\n\n[^13_regressions-2]: Be aware that such insights might also fundamentally question the relationship between variables, i.e. are the measures truly independent variables or rather dependent ones?\n\nAs a final step, we should remove the variables that are not significant and see how this affects our model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(new_cases ~ movements + schools + businesses + travel,\n         data = covid_uk_ger)\n\nbroom::tidy(m1) |>\n  mutate(p.value = round(p.value, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)  -3024.     724.       -4.18       0\n2 movements      -64.0     13.4      -4.79       0\n3 schools        382.      28.8      13.3        0\n4 businesses      90.5     12.9       7.01       0\n5 travel          45.7      9.17      4.99       0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Evaluate the quality of our model\nperformance::model_performance(m1) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1\nColumns: 7\n$ AIC         <dbl> 25279.52\n$ AICc        <dbl> 25279.59\n$ BIC         <dbl> 25310\n$ R2          <dbl> 0.2294056\n$ R2_adjusted <dbl> 0.2268\n$ RMSE        <dbl> 10052.12\n$ Sigma       <dbl> 10073.34\n```\n\n\n:::\n:::\n\n\nComparing our original model `m0` with our revised model `m1`, we can see that our `R2 (adj.)` barely changed. Thus, `m1` is a superior model because it can explain (almost) the same amount of variance but with fewer predictors. The model `m1` would also be called a *parsimonious model*, i.e. a model that is simple but has good predictive power. When reading about multiple regressions, you might often hear people mention the *'complexity'* of a model, which refers to the number of predictors. The complexity of a model is known as the *'degrees of freedom (df) of the numerator'* and is computed as $number\\ of\\ preditors - 1$. For example, in our model of 4 independent variables, the *df* of the numerator is 3. This value is relevant when computing the power of a regression model (see also @sec-power-analysis).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::compare_performance(m0, m1) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 12\n$ Name        <chr> \"m0\", \"m1\"\n$ Model       <chr> \"lm\", \"lm\"\n$ AIC         <dbl> 25277.62, 25279.52\n$ AIC_wt      <dbl> 0.72085, 0.27915\n$ AICc        <dbl> 25277.74, 25279.59\n$ AICc_wt     <dbl> 0.7156888, 0.2843112\n$ BIC         <dbl> 25318.26, 25310.00\n$ BIC_wt      <dbl> 0.01580738, 0.98419262\n$ R2          <dbl> 0.2332214, 0.2294056\n$ R2_adjusted <dbl> 0.2293258, 0.2268000\n$ RMSE        <dbl> 10027.20, 10052.12\n$ Sigma       <dbl> 10056.88, 10073.34\n```\n\n\n:::\n:::\n\n\nHowever, there are a couple of things we overlooked when running this regression. If you are familiar with regressions already, you might have been folding your hands over your face and burst into tears about the blasphemous approach to linear regression modelling. Let me course-correct at this point.\n\nSimilar to other parametric approaches, we need to test for sources of bias, linearity, normality and homogeneity of variance. Since multiple regressions consider more than one variable, we must consider these criteria in light of other variables. As such, we have to draw on different tools to assess our data. There are certain pre- and post-tests we have to perform to evaluate and develop a multiple regression model fully:\n\n-   *Pre-test*: We need to consider whether there are any outliers and whether all assumptions of OLS regression models are met.\n\n-   *Post-test*: We need to check whether our independent variables correlate very strongly with each other, i.e. are there issues of multiple collinearity.\n\nWe already covered aspects of linearity, normality and homogeneity of variance. However, outliers and collinearity have to be reconsidered for multiple regressions.\n\n### Outliers in multiple regressions {#sec-outliers-in-multiple-regressions}\n\nWhile it should be fairly clear by now why we need to handle outliers (remember @sec-dealing-with-outliers), our approach is somewhat different when we need to consider multiple variables at once. Instead of identifying outliers for each variable independently, we have to consider the interplay of variables. In other words, we need to find out how an outlier in our independent variable affects the overall model rather than just one other variable. Thus, we need a different technique to assess outliers. By now, you might not be shocked to find that there is more than one way of identifying outliers in regressions and that there are many different ways to compute them in *R*. [@cohen2014applied] distinguishes between where one can find outliers in the model as summarised in @tbl-outliers-in-multiple-regressions). I offer a selection of possible ways to compute the relevant statistics, but this list is not exhaustive. For example, many of these statistics can also be found using the function `influence.measures()` that comes with the base *R* functions when installing it.\n\n+------------------------+--------------------------------------+---------------------------------------------------------------------------------------+\n| Outlier in?            | Measures                             | function in *R*                                                                       |\n+========================+======================================+=======================================================================================+\n| *Dependent variable*   | -   Internally studentised residuals | -   `rstandard()` or `fortify()`                                                      |\n+------------------------+--------------------------------------+---------------------------------------------------------------------------------------+\n| *Dependent variable*   | -   Externally studentised residuals | -   `rstudent()`                                                                      |\n+------------------------+--------------------------------------+---------------------------------------------------------------------------------------+\n| *Independent variable* | -   Leverage                         | -   `hatvalues()` or `fortify()`                                                      |\n+------------------------+--------------------------------------+---------------------------------------------------------------------------------------+\n| *Independent variable* | -   Mahalanobis distance             | -   `mahalanobis()`[^13_regressions-3] or `mahalanobis_distance()`[^13_regressions-4] |\n+------------------------+--------------------------------------+---------------------------------------------------------------------------------------+\n| *Entire model*         | *Global measures of influence*       | *Global measures of influence*                                                        |\n|                        |                                      |                                                                                       |\n|                        | -   DFFITS,                          | -   `dffits()`                                                                        |\n|                        |                                      |                                                                                       |\n|                        | -   Cook's d                         | -   `cooks.distance()` or `fortify()`                                                 |\n+------------------------+--------------------------------------+---------------------------------------------------------------------------------------+\n| *Entire model*         | *Specific measures of influence:*    | *Specific measures of influence:*                                                     |\n|                        |                                      |                                                                                       |\n|                        | -   DFBETAS                          | -   `dfbetas()`                                                                       |\n+------------------------+--------------------------------------+---------------------------------------------------------------------------------------+\n\n: Outlier detection in multiple regressions {#tbl-outliers-in-multiple-regressions}\n\n[^13_regressions-3]: This function does not take the model as an attribute, but instead requires the data, the column means and the covariance. Thus, we have to specify this function in the following way: `mahalanobis(data, colMeans(data), cov(data))`\n\n[^13_regressions-4]: Function from `rstatix` package which automatically classifies values as outliers for us.\n\nWhile it might be clear why we need to use different approaches to find outliers in different model components, this might be less clear when evaluating outliers that affect the entire model. We distinguish between *global measures of influence*, which identify how a single observation affects the quality of the entire model, and *specific measures of influence*, which determine how a single observation affects each independent variable, i.e. its regression coefficients denoted as $\\beta$. It is recommended to look at all different outlier measures before venturing ahead to perform linear multiple regression. Going through the entire set of possible outliers would go way beyond the scope of this book. So, I will focus on five popular measures which cover all three categories:\n\n-   Dependent variable: Externally studentised residuals\n\n-   Independent variable: Leverage and Mahalanobis distance\n\n-   Entire model: Cook's d and DFBETAS\n\nThe approach taken is the same for the other outlier detection methods, but with different functions. Thus, it should be quite simple to reproduce these as well after having finished the chapters below.\n\n#### Outliers in the dependent variable {#sec-outliers-in-the-dependent-variable}\n\nIrrespective of whether we look at independent or dependent variables, we always want to know whether extreme values are present. Here I will use the externally studentised residual, which 'is the preferred statistic to use to identify cases whose (...) values are highly discrepant from their predicted values' [@cohen2014applied] (p.401).\n\nFirst, we need to compute the residuals for our model as a new column in our dataset. Since we also want to use other methods to investigate outliers, we can use the function `fortify()`, which will add some of the later indicators and creates a `tibble` that only includes the variables from our model. This one handy function does a lot of things at once. In a second step, we add the studentised residuals using `rstudent()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a tibble with some pre-computed stats\nm1_outliers <-\n  fortify(m1) |>\n  as_tibble()\n\nglimpse(m1_outliers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,188\nColumns: 11\n$ new_cases  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ movements  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ schools    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ businesses <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ travel     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ .hat       <dbl> 0.005159386, 0.005159386, 0.005159386, 0.00515938…\n$ .sigma     <dbl> 10077.22, 10077.22, 10077.22, 10077.22, 10077.22,…\n$ .cooksd    <dbl> 9.393496e-05, 9.393496e-05, 9.393496e-05, 9.39349…\n$ .fitted    <dbl> -3023.617, -3023.617, -3023.617, -3023.617, -3023…\n$ .resid     <dbl> 3023.617, 3023.617, 3023.617, 3023.617, 3023.617,…\n$ .stdresid  <dbl> 0.3009375, 0.3009375, 0.3009375, 0.3009375, 0.300…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add the externally studentised residuals\nm1_outliers <-\n  m1_outliers |>\n  mutate(.studresid = rstudent(m1))\n\nglimpse(m1_outliers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,188\nColumns: 12\n$ new_cases  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ movements  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ schools    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ businesses <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ travel     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ .hat       <dbl> 0.005159386, 0.005159386, 0.005159386, 0.00515938…\n$ .sigma     <dbl> 10077.22, 10077.22, 10077.22, 10077.22, 10077.22,…\n$ .cooksd    <dbl> 9.393496e-05, 9.393496e-05, 9.393496e-05, 9.39349…\n$ .fitted    <dbl> -3023.617, -3023.617, -3023.617, -3023.617, -3023…\n$ .resid     <dbl> 3023.617, 3023.617, 3023.617, 3023.617, 3023.617,…\n$ .stdresid  <dbl> 0.3009375, 0.3009375, 0.3009375, 0.3009375, 0.300…\n$ .studresid <dbl> 0.3008218, 0.3008218, 0.3008218, 0.3008218, 0.300…\n```\n\n\n:::\n:::\n\n\nWith our dataset ready for plotting, we can do exactly that and see which observations are particularly far away from the rest of our `.studresid` values. To plot each observation separately, we need an id variable for each row. We can quickly add one by using the function `rownames_to_column()`. This way, we can identify each column and also `filter()` out particular rows. You might be able to guess why this will come in handy at a later stage of our outlier analysis (hint: @sec-reviewing-the-outliers).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create an ID column\nm1_outliers <- m1_outliers |> rownames_to_column()\n\nm1_outliers |>\n  ggplot(aes(x = rowname,\n             y = .studresid)) +\n  geom_point(size = 0.5)\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/externally-studentised-residuals-plot-1.png){fig-alt='This plot displays standardized residuals (studresid) across different row identifiers on the x-axis, representing individual observations. The scores fluctuate around zero, with noticeable clusters and outliers.' width=672}\n:::\n:::\n\n\nThe values of the externally studentised residuals can be positive or negative. All we need to know is which values count as outliers and which ones do not. @cohen2014applied (p. 401) provides some guidance:\n\n-   general: $outlier = \\pm 2$\n\n-   bigger samples: $outlier = \\pm 3$ or $\\pm 3.5$ or $\\pm 4$\n\nAs you can tell, it is a matter of well-informed personal judgement. Our dataset consists of over 1200 observations. As such, the data frame certainly counts as large. We can take a look and see how many outliers we would get for each of the benchmarks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout_detect <-\n  m1_outliers |>\n  mutate(pm_2 = ifelse(abs(.studresid) > 2, \"TRUE\", \"FALSE\"),\n         pm_3 = ifelse(abs(.studresid) > 3, \"TRUE\", \"FALSE\"),\n         pm_35 = ifelse(abs(.studresid) > 3.5, \"TRUE\", \"FALSE\"),\n         pm_4 = ifelse(abs(.studresid) > 4, \"TRUE\", \"FALSE\"))\n\nout_detect |> count(pm_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  pm_2      n\n  <chr> <int>\n1 FALSE  1132\n2 TRUE     56\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nout_detect |> count(pm_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  pm_3      n\n  <chr> <int>\n1 FALSE  1171\n2 TRUE     17\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nout_detect |> count(pm_35)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  pm_35     n\n  <chr> <int>\n1 FALSE  1173\n2 TRUE     15\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nout_detect |> count(pm_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  pm_4      n\n  <chr> <int>\n1 FALSE  1179\n2 TRUE      9\n```\n\n\n:::\n:::\n\n\nThe results indicate we could have as many as `56` outliers and as little as `9`. It becomes apparent that choosing the right threshold is a tricky undertaking. Let's plot the data again to make it easier to read and add some of the thresholds. I skip `3.5` since it is very close to `3`. I also reorder the observations (i.e. the x-axis) based on `.studresid` using `reorder()` which improves readability substantially.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_outliers |>\n  ggplot(aes(x = reorder(rowname, .studresid),\n             y = .studresid)) +\n  geom_point(size = 0.5) +\n  \n  # Adding horizontal lines as thresholds\n  geom_hline(yintercept = c(-2, 2), col = \"green\") +\n  geom_hline(yintercept = c(-3, 3), col = \"orange\") +\n  geom_hline(yintercept = c(-4, 4), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/plot-outliers-ext-stud-resid-1.png){fig-alt='This plot shows ordered standardized residuals (studresid) with reference lines in green, orange and red, marking significant thresholds. Points outside these lines highlight potential outliers.' width=672}\n:::\n:::\n\n\nAt this point, it is a matter of choosing the threshold that you feel is most appropriate. More importantly, though, you have to make sure you are transparent in your choices and provide some explanations around your decision-making. For example, a threshold of `2` appears too harsh for my taste and identifies too many observations as outliers. On the other hand, using the orange threshold of `3` seems to capture most observations I would consider an outlier because we can also visually see how the dots start to look less like a straight line and separate more strongly. Besides, @cohen2014applied also suggests that a threshold of `3` is more suitable for larger datasets. Finally, since we have an ID column (i.e. `rownames`), we can also store our outliers in a separate object to easily reference them later for comparisons with other measures. Again, the purpose of doing this will become evident in @sec-reviewing-the-outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutliers <-\n  out_detect |>\n  select(rowname, pm_3) |>\n  rename(studresid = pm_3)\n```\n:::\n\n\nThere are still more diagnostic steps we have to take before deciding which observations we want to remove or deal with in other ways (see also @sec-dealing-with-outliers).\n\n#### Outliers in independent variables {#sec-outliers-in-the-independent-variables}\n\nTo identify outliers in independent variables, we can use *Leverage scores* or the *Mahalanobis distances*. Both are legitimate approaches and can be computed very easily.\n\nFor the leverage scores, we can find them already in our `fortify()`-ed dataset `m1_outliers`. They are in the column `.hat`. An outlier is defined by the distance from the average leverage value, i.e. the further the distance of an observation from this average leverage, the more likely we have to classify it as an outlier. The average leverage is computed as follows:\n\n::: {#average-leverage-equation align=\"center\"}\n$average\\ leverage = \\frac{k + 1}{n}$\n:::\n\nIn this equation, *k* stands for the number of predictors (i.e. 6) and *n* for the number of observations (i.e. 1188). Therefore, our average leverage can be computed as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(avg_lvg <- (6 + 1) / 1188)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.005892256\n```\n\n\n:::\n:::\n\n\nSimilar to before, we find different approaches to setting cut-off points for this indicator. While @hoaglin1978hat argue that a distance twice the average counts as an outlier, @stevens2012applied (p. 105) suggests that values three times higher than the average leverage will negatively affect the model. The rationale is the same as for the externally studentised residuals: If the thresholds are too low, we might find ourselves with many observations, which we would have to investigate further. This might not always be possible or even desirable. However, this should not imply that many outliers are not worth checking. Instead, if there are many, one would have to raise questions about the model itself and whether an important variable needs adding to explain a series of observations that appear to be somewhat 'off'.\n\nLet's plot the leverages and use @stevens2012applied benchmark to draw our reference line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_outliers |>\n  ggplot(aes(x = reorder(rowname, .hat),\n             y = .hat)) +\n  geom_point(size = 0.5) +\n  geom_hline(yintercept = 3 * avg_lvg, col = \"orange\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/avg-lvg-plot-1.png){fig-alt='This plot shows ordered leverage values (.hat) for observations, with n orange horizontal line marking a threshold for high leverage, indicating potential outliers.' width=672}\n:::\n:::\n\n\nAs before, we want to know which observations fall beyond the threshold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_outliers <-\n  m1_outliers |>\n  mutate(avglvg = ifelse(.hat > 3 * avg_lvg, \"TRUE\", \"FALSE\")) |>\n  select(rowname, avglvg)\n\n# Add new results to our reference list\noutliers <- left_join(outliers, new_outliers, by = \"rowname\")\n```\n:::\n\n\nLooking at our reference object `outliers`, you will notice that both methods (`studresid` and `avglvg`) detect different outliers. Thus, the detection of outliers depends on where we look, i.e. dependent variable or independent variable.\n\nThe second method I will cover in this section is the Mahalanobis distance. Luckily the `rstatix` package includes a handy function `mahalanobis_distance()` which automatically detects outliers and classifies them for us.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmhnbs_outliers <-\n  m1_outliers |>\n  \n  # Select only columns which represent independent variables\n  select(new_cases:travel) |>\n  \n  # Compute the Mahalanobis distance\n  rstatix::mahalanobis_distance() |>\n  \n  # Reformat the output to fit our 'outliers' dataset\n  rownames_to_column() |>\n  select(rowname, mahal.dist, is.outlier) |>\n  rename(mhnbs = is.outlier)\n\n# Add new results to our reference list\noutliers <- left_join(outliers, mhnbs_outliers, by = \"rowname\")\n\nglimpse(outliers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,188\nColumns: 5\n$ rowname    <chr> \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\"…\n$ studresid  <chr> \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE\", \"FAL…\n$ avglvg     <chr> \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE\", \"FAL…\n$ mahal.dist <dbl> 5.215, 5.215, 5.215, 5.215, 5.215, 5.215, 5.215, …\n$ mhnbs      <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# We need to remove mahal.dist because it does not indicate\n# whether a value is an outlier #data-cleaning\noutliers <- outliers |> select(-mahal.dist)\n```\n:::\n\n\nWhile it is very convenient that this function picks the cut-off point for us, it might be something we would want more control over. As we have learned so far, choosing the 'right' cut-off point is essential. Since the values follow a chi-square distribution, we can determine the cut-off points based on the relevant critical value at the chosen p-value. *R* has a function that allows finding the critical value for our model, i.e. `qchisq()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(mhnbs_th <- qchisq(p = 0.05,\n                    df = 4,\n                    lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.487729\n```\n\n\n:::\n:::\n\n\nThe `p`-value reflects the probability we are willing to accept that our result is significant/not significant (remember Type I error in @sec-power-analysis). The value `df` refers to the degrees of freedom, which relates to the number of independent variables, i.e. `4`. Thus, it is fairly simple to identify a cut-off point yourself by choosing the `p`-value you consider most appropriate. The function `mahalanobis_distance()` assumes $p = 0.01$, which is certainly a good but strict choice.\n\nIf we want to plot outliers as before, we can reuse our code from above and replace it with the relevant new variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmhnbs_outliers |>\n  ggplot(aes(x = reorder(rowname, mahal.dist),\n             y = mahal.dist)) +\n  geom_point(size = 0.5) +\n  geom_hline(yintercept = mhnbs_th, col = \"orange\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/mahalanobis-distance-plot-1.png){fig-alt='This plot displays ordered Mahalanobis distances, with an orange horizontal line indicating a threshold, used to identify potential outliers in the dataset.' width=672}\n:::\n:::\n\n\nLooking at our `outliers`, we notice that the Mahalanobis distance identifies more outliers than the leverage, but the same ones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutliers |> filter(avglvg == \"TRUE\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 × 4\n   rowname studresid avglvg mhnbs\n   <chr>   <chr>     <chr>  <lgl>\n 1 224     FALSE     TRUE   TRUE \n 2 225     FALSE     TRUE   TRUE \n 3 226     FALSE     TRUE   TRUE \n 4 227     FALSE     TRUE   TRUE \n 5 969     FALSE     TRUE   TRUE \n 6 970     FALSE     TRUE   TRUE \n 7 971     FALSE     TRUE   TRUE \n 8 972     FALSE     TRUE   TRUE \n 9 973     FALSE     TRUE   TRUE \n10 974     FALSE     TRUE   TRUE \n11 975     FALSE     TRUE   TRUE \n12 976     FALSE     TRUE   TRUE \n13 977     FALSE     TRUE   TRUE \n14 978     FALSE     TRUE   TRUE \n15 979     FALSE     TRUE   TRUE \n16 980     FALSE     TRUE   TRUE \n17 981     FALSE     TRUE   TRUE \n18 982     FALSE     TRUE   TRUE \n```\n\n\n:::\n:::\n\n\nThus, whether you need to use both approaches for the same study is questionable and likely redundant. Still, in a few edge cases, you might want to double-check the results, especially when you feel uncertain which observations should be dealt with later. But, of course, it does not take much time to consider both options.\n\nBesides looking at each side of the regression separately, we might also consider whether removing an observation significantly affects all variables. This is done with outlier detection diagnostics which consider the entire model.\n\n#### Outlier detection considering the entire model: Global measures {#sec-outlier-detection-global-measures}\n\nTo assess the global impact of outliers on the entire regression model, *Cook's d* [@cook1982residuals] is a popular method in the Social Sciences. It measures to which extend a single observation can affect the predictive power of our model to explain all other observations. Obviously, we do not wish to keep observations that make predicting most of the other observations more challenging. However, as shown in @tbl-outliers-in-multiple-regressions, there are different approaches to this, but some are rather redundant. For example, @cohen2014applied highlight that DDFITS and Cook's d are 'interchangeable statistics' (p. 404). Thus, there is no point in demonstrating both since they function similarly. Your decision might be swayed by the preferences of a publisher, editor, lecturer, supervisor or reviewer. Here, I will focus on *Cook's d* since it is the approach I see most frequently used in my field. By all means, feel encouraged to go the extra mile and perform the same steps for the DDFITS.\n\nThe good news, `fortify()` automatically added `.cooksd` to our dataset `m1_outliers`. Thus, we can immediately compute whether outliers exist and inspect them visually as we did before. A promising starting point to find outliers via the Cook's D is to plot its distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_outliers |>\n  ggplot(aes(x = rowname,\n             y = .cooksd)) +\n  geom_col()\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/cooks-d-plot-1.png){fig-alt='This plot shows Cook’s distance values across observations as a bar plot, highlighting points with high influence on the model fit. Peaks indicate potential influential data points of which there are at least three very obvious ones, but none reaches a value of one or higher.' width=672}\n:::\n:::\n\n\nInspecting this barplot, we can tell that some observations have much higher `.cooksd` values than any other observation. Once again, we first need to decide on a benchmark to determine whether we can consider these values as outliers. If we follow @cook1982residuals, values that are higher than 1 (i.e. $d > 1$) require reviewing. Looking at our plot, none of the observations reaches `1`, and we need not investigate outliers. Alternatively, @cohen2014applied suggest that other benchmarks are also worth considering, for example, based on the critical value of an F distribution, which we can determine with the function `qf()`. This requires us to determine two degrees of freedom ($df_1$ and $df_2$) and a p-value. To determine these values, @cohen2014applied suggests $p = 0.5$ and the following formulas to determine the correct $df$:\n\n::: {#critical-value-cooks-d align=\"center\"}\n$df_1 = k +1$\n\n$df_2 = n - k - 1$\n:::\n\nLike the critical value for [average leverage](#average-leverage-equation \"average leverage\"), $k$ reflects the number of predictors, and $n$ refers to the sample size. Thus, we can determine the critical value, and therefore our cut-off point as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf(p = 0.5,\n   df1 = 4 + 1,\n   df2 = 1188 - 6 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8707902\n```\n\n\n:::\n:::\n\n\nThis score would also imply that we have no particular outliers to consider, because the highest value in `.cooksd` is 0.09 computed via `max(m1_outliers$.cooksd)`.\n\nWe might be led to believe that our work is done here, but @cohen2014applied recommends that any larger deviation is worth inspecting. We do notice that relative to other observations, some cases appear extreme. Ideally, one would further investigate these cases and compare the regression results by removing such extreme cases iteratively. This way, one can assess whether the extreme observations genuinely affect the overall estimates of our model. This would imply repeating steps we already covered earlier when performing multiple regressions with and without outliers. Thus, I will forgo this step here.\n\nIn the last chapter about outliers (@sec-reviewing-the-outliers), we will rerun the regression without outliers to see how this affects our model estimates. However, before we can do this, we have to cover one more method of detecting outliers.\n\n#### Outlier detection considering the entire model: Specific measures {#sec-outlier-detection-specific-measures}\n\nWhile Cook's d helps us identify outliers that affect the quality of the entire model, there is also a way to investigate how outliers affect specific predictors. This is achieved with DFBETAS, which, similar to previous methods, assesses the impact of outliers by removing them and measures the impact of such removal on other parts of the regression model.\n\nThe function `dfbetas()` takes our model `m1` and returns the statistics for each predictor in the model. Thus, we do not receive a single score for each observation but multiple for each specific predictor, i.e. each specific measure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_dfbetas <-\n  dfbetas(m1) |>\n  as_tibble() |>               # convert to tibble for convenience\n  rownames_to_column()          # add our rownames\n\nglimpse(m1_dfbetas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,188\nColumns: 6\n$ rowname       <chr> \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"…\n$ `(Intercept)` <dbl> 0.02166365, 0.02166365, 0.02166365, 0.02166365…\n$ movements     <dbl> -0.0008908373, -0.0008908373, -0.0008908373, -…\n$ schools       <dbl> -0.01412839, -0.01412839, -0.01412839, -0.0141…\n$ businesses    <dbl> -0.002957931, -0.002957931, -0.002957931, -0.0…\n$ travel        <dbl> -0.005546516, -0.005546516, -0.005546516, -0.0…\n```\n\n\n:::\n:::\n\n\nAll we have to do now is to compare the scores against a benchmark for each variable in this dataset, and we know which observations substantially affect one of the predictors. @cohen2014applied provides us with the following recommendations for suitable thresholds:\n\n-   small or moderate datasets: $DFBETAS > \\pm 1$\n\n-   large datasets: $DFBETAS > \\pm\\frac{2}{\\sqrt(n)}$\n\nSince our dataset falls rather into the 'large' camp, we should choose the second option. Again, $n$ stands for the sample size. Let's create an object to store this value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(dfbetas_th <- 2 / sqrt(1188))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05802589\n```\n\n\n:::\n:::\n\n\nFor demonstration purposes, I will pick `movements` to check for outliers. If this was a proper analysis for a project, you would have to compare this indicator against each variable separately. As the benchmarks indicate, the DFBETAS value can be positive or negative. So, when we compare the calculated values with it, we can look at the absolute value, i.e. use `abs()`, which turns all values positive. This makes it much easier to compare observations against a threshold and we could do this for any assessment of outliers against a benchmark.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check whether values exceed the threshold\ndfbetas_check <-\n  m1_dfbetas |>\n  mutate(dfbetas_movements = ifelse(abs(movements) > dfbetas_th,\n                                \"TRUE\",\n                                \"FALSE\")) |>\n  select(rowname, dfbetas_movements)\n\n# Add result to our outliers object\noutliers <-\n  outliers |>\n  left_join(dfbetas_check, by = \"rowname\")\n\nglimpse(outliers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,188\nColumns: 5\n$ rowname           <chr> \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9…\n$ studresid         <chr> \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE…\n$ avglvg            <chr> \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE…\n$ mhnbs             <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ dfbetas_movements <chr> \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE\", \"FALSE…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# some housekeeping, i.e. making all columns <lgl> except for rowname\noutliers <-\n  outliers |>\n  mutate(rowname = as_factor(rowname)) |>\n  mutate_if(is.character, as.logical)\n\nglimpse(outliers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,188\nColumns: 5\n$ rowname           <fct> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,…\n$ studresid         <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ avglvg            <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ mhnbs             <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n$ dfbetas_movements <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n```\n\n\n:::\n:::\n\n\nOf course, we can also visualise the outliers as we did before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_dfbetas |>\n  ggplot(aes(x = rowname,\n             y = movements)) +\n  geom_point(size = 0.5) +\n  geom_hline(yintercept = dfbetas_th, col = \"red\") +\n  geom_hline(yintercept = -dfbetas_th, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/dfbetas-plot-outliers-1.png){fig-alt='This plot visualizes the ‘movements’ variable across observations, with red lines marking threshold boundaries. Observations outside these boundaries may be considered outliers.' width=672}\n:::\n:::\n\n\nI want to take this opportunity to show that sometimes we can make visualisations even simpler. Remember, we used `abs()` to make all values positive? We can apply the same principle here. This way, we only need one line to indicate the threshold. In addition, we could also plot multiple variables at once. Instead of defining the `aes()` inside the `ggplot()` function, we can define it independently for each `geom_point()`. What do you think about the following version of the same plot?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_dfbetas |>\n  ggplot() +\n  \n  # Create dot plot for the variable movements\n  geom_point(aes(x = reorder(rowname, abs(movements)),\n                 y = abs(movements),\n                 col = \"movements\"),\n             size = 0.5,\n             alpha = 0.5) +\n  \n  # Create dot plot for the variable travel\n  geom_point(aes(x = rowname,\n                 y = abs(travel),\n                 col = \"travel\"),\n             size = 0.5,\n             alpha = 0.5) +\n  \n  # Add threshold line\n  geom_hline(yintercept = dfbetas_th, col = \"#FF503A\") +\n  \n  # Apply different colours to each dot plot\n  scale_color_manual(values = c(\"movements\" = \"#2EA5FF\",\n                                \"travel\" = \"#7DB33B\")) +\n\n  # Label the legend appropriately\n  labs(col = \"COVID measures\")\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/dfbetas-plot-outliers-alternative-1.png){fig-alt='This plot shows the absolute values of ‘movements’ and ‘travel’ data points sorted in ascending order. A red line indicates a threshold level.Values above this line can be considered outliers related to COVID measures.' width=672}\n:::\n:::\n\n\nAfter `reorder()`ing the variable `movements` and plotting `travel` as well, we notice that there might be slightly fewer outliers for `movements` than for `travel`. Thus, some observations affect some predictors more strongly than others.\n\n#### Reviewing the outliers {#sec-reviewing-the-outliers}\n\nAfter all this hard work and what turned out to be a very lengthy chapter, we finally arrive at the point where we check which observations we might wish to remove or handle in some shape or form. First, we want to know which observations are affected. Therefore we need to review our reference data in the object `outliers`. We want to see all observations that were identified as an outlier by one or more diagnostic tool. There are two ways to achieve this. First, we can use what we have learned so far and `filter()` each column for the value TRUE. This is the hard way of doing it, and if you have many more columns, this will take a little while and potentially drive you insane. The easy (and clever) way of filtering across multiple columns can be achieved by turning multiple columns into a single column. In the `tidyverse`, this is called `pivot_longer()` and we performed it earlier in @sec-sphericity. Thus, it might seem less complicated than expected. Let's do this step-by-step as we did for `pivot_wider()` in @sec-chi-squared-test. Currently, our data has five columns, of which four are different measures to detect outliers. Our goal is to create a table that has only three columns:\n\n-   `rowname`, which we keep unchanged because it is the ID that identifies each observation in our data\n\n-   `outlier_measure`, which is the variable that indicates which measure was used to find an outlier.\n\n-   `is.outlier`, which contains the values from the tibble, i.e. the cell values of `TRUE` and `FALSE`.\n\nHere is an example of what we want to achieve. Imagine we have a smaller dataset, which contains three columns, two of which are outlier detection measures, i.e. `studresid` and `mhbns`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- tribble(\n  ~rowname,   ~ studresid,    ~mhbns,\n         \"1\",       FALSE,     FALSE,\n         \"2\",        TRUE,     FALSE,\n         \"3\",        TRUE,      TRUE\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  rowname studresid mhbns\n  <chr>   <lgl>     <lgl>\n1 1       FALSE     FALSE\n2 2       TRUE      FALSE\n3 3       TRUE      TRUE \n```\n\n\n:::\n:::\n\n\nTo filter for outliers using a single column/variable, we need to rearrange the values in `studresid` and `mhbns`. We currently have one column which captures the `rowname`, and two other columns which are both outlier detection methods. Thus, we could argue that `studresid` and `mhbns` measure the same, but with different methods. Therefore we can combine them into a factor, e.g. `is.outlier`, with two levels reflecting each outlier detection method. At the moment, we have two values recorded for every row in this dataset. For example, the first observation has the values `studresid == FALSE` and `mhnbs == FALSE`. If we want to combine these two observations into a single column, we need to have two rows with the `rowname` `1` to ensure that each row still only contains one observation, i.e. a tidy dataset. Therefore, we end up with more rows than our original dataset, hence, a 'longer' dataset. Here is how we can do this automatically:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_long <-\n  data |>\n  pivot_longer(cols = !rowname,\n               names_to = \"outlier_measure\",\n               values_to = \"is.outlier\")\n\ndata_long\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  rowname outlier_measure is.outlier\n  <chr>   <chr>           <lgl>     \n1 1       studresid       FALSE     \n2 1       mhbns           FALSE     \n3 2       studresid       TRUE      \n4 2       mhbns           FALSE     \n5 3       studresid       TRUE      \n6 3       mhbns           TRUE      \n```\n\n\n:::\n:::\n\n\nInstead of three rows, we have six, and all the outlier detection values (i.e. all `TRUE` and `FALSE` values) are now in one column, i.e. `is.outlier`. However, what exactly did just happen in this line of code? In light of what we specified above, we did three things inside the function `pivot_longer()`:\n\n-   We excluded `rownames` from being pivoted, i.e. `cols = !rowname`. The `!` means *not* in this context.\n\n-   We specified a column where all the column names go to, i.e. `names_to = \"outlier_measure\"`.\n\n-   We defined a column where all cell values should be listed, i.e. `values_to = \"is.outlier\"`.\n\nFrom here, it is straightforward to `count()` the number of `is.outlier` per `rowname` and `filter()` out those that return a value of `TRUE`. Everything we learned is now easily applicable without overly complicated functions or many repetitions. As mentioned earlier, pivoting datasets is an essential data wrangling skill, not matter which software you prefer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_long |>\n  count(rowname, is.outlier) |>\n  filter(is.outlier == \"TRUE\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  rowname is.outlier     n\n  <chr>   <lgl>      <int>\n1 2       TRUE           1\n2 3       TRUE           2\n```\n\n\n:::\n:::\n\n\nEt voilà. We now counted the number of times an observation was detected considering both measures. This is scalable to more than two measures. Thus, we can apply it to our data as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutliers_true <-\n  outliers |>\n  pivot_longer(!rowname,\n               names_to = \"measure\",\n               values_to = \"is.outlier\") |>\n  count(rowname, is.outlier) |>\n  filter(is.outlier == \"TRUE\")\n\noutliers_true\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 85 × 3\n   rowname is.outlier     n\n   <fct>   <lgl>      <int>\n 1 224     TRUE           2\n 2 225     TRUE           2\n 3 226     TRUE           2\n 4 227     TRUE           2\n 5 344     TRUE           1\n 6 345     TRUE           1\n 7 346     TRUE           1\n 8 349     TRUE           1\n 9 350     TRUE           1\n10 351     TRUE           1\n# ℹ 75 more rows\n```\n\n\n:::\n:::\n\n\nThe result is a `tibble` which tells us that we identified 85 distinct outliers. This might sound like a lot, but we also have to remember that our dataset consists of 1188 observations, i.e. 7% of our data are outliers.\n\nSince the output is relatively long, we might want to plot the outcome to get an idea of the bigger picture.\n\n\n::: {.cell fg-alt='A bar plot which displays how many analytical tools identified the same observation as an outlier. Most rows show only a score of 1, with fewer rows at values of 2 and 3.'}\n\n```{.r .cell-code}\noutliers_true |>\n  ggplot(aes(x = reorder(rowname, n),\n             y = n)) +\n  geom_col() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/number-of-outliers-plot-1.png){width=672}\n:::\n:::\n\n\nA few observations were detected by three out of the four methods we used to detect outliers. There are some more which were detected by two different methods. However, there are also more than half of our outliers which were only detected by one method.\n\nAs highlighted in @sec-dealing-with-outliers, there are many ways we can go about outliers. To keep our analysis simple, I intend to remove those observations detected by multiple methods rather than only by one. Whether this approach is genuinely appropriate is a matter of further investigation. I take a very pragmatic approach with our sample data. However, it is worth reviewing the options available to transform data, as covered by @field2013discovering (p.203). Data transformation can help to deal with outliers instead of removing or imputing them. Still, data transformation comes with severe drawbacks and in most cases, using a bootstrapping technique to account for violations of parametric conditions is often more advisable. Bootstrapping refers to the process of randomly resampling data from your dataset and rerun the same test multiple times, e.g. 2000 times. Thus, there will be some samples that do not include the outliers. The process is somewhat similar to multiple imputation (see @sec-replacing-removing-missing-data). Still, instead of estimating a specific value in our dataset, we estimate statistical parameters, e.g. confidence intervals or regression coefficients (i.e. estimates). The package `rsample` allows implementing bootstrapping straightforwardly. However, bootstrapping comes at the cost of lower power because we are running the test so many times.\n\nFor now, I settle on removing outliers entirely. The easiest way to remove these outliers is to combine our `outliers` dataset with our regression (`m1_outliers`). Now you will notice that having `rowname` as an ID allows us to match the values of each table to each other. Otherwise, this would not be possible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Include outliers which were detected by multiple methods\noutliers_select <-\n  outliers_true |>\n  filter(n > 1)\n\n# Keep only columns which are NOT included in outliers_select\nm1_no_outliers <- anti_join(m1_outliers, outliers_select,\n                            by = \"rowname\")\n\nm1_no_outliers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,152 × 13\n   rowname new_cases movements schools businesses travel    .hat\n   <chr>       <dbl>     <dbl>   <dbl>      <dbl>  <dbl>   <dbl>\n 1 1               0         0       0          0      0 0.00516\n 2 2               0         0       0          0      0 0.00516\n 3 3               0         0       0          0      0 0.00516\n 4 4               0         0       0          0      0 0.00516\n 5 5               0         0       0          0      0 0.00516\n 6 6               0         0       0          0      0 0.00516\n 7 7               0         0       0          0      0 0.00516\n 8 8               0         0       0          0      0 0.00516\n 9 9               0         0       0          0      0 0.00516\n10 10              0         0       0          0      0 0.00516\n# ℹ 1,142 more rows\n# ℹ 6 more variables: .sigma <dbl>, .cooksd <dbl>, .fitted <dbl>,\n#   .resid <dbl>, .stdresid <dbl>, .studresid <dbl>\n```\n\n\n:::\n:::\n\n\nThe function `anti_join()` does exactly what the name implies. It takes the first data frame (i.e. `m1_outliers`) and removes values that are included in the second data frame (i.e. `outliers_select()`). This is tremendously helpful when performing such complex outlier detection and removing them all in one go.\n\nAs the final step, we want to compare how the removal of outliers affected our model. Ideally, we managed to improve the regression. Thus, we compare our old model `m1` with a new model `m2`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Original regression\nm1 <- lm(new_cases ~ movements + schools + businesses + travel,\n         data = covid_uk_ger)\n\n# Regression with outliers removed\nm2 <- lm(new_cases ~ movements + schools + businesses + travel,\n         data = m1_no_outliers)\n\n# Compare the parameters between models\n# I added some reformatting, because\n# I prefer a regular tibble over a pre-formatted\n# table. Technically you only need the first line.\n\nparameters::compare_parameters(m1, m2) |>\n  as_tibble() |>\n  select(Parameter, Coefficient.m1, p.m1, Coefficient.m2, p.m2) |>\n  mutate(across(where(is.numeric), \\(x) round(0, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  Parameter   Coefficient.m1  p.m1 Coefficient.m2  p.m2\n  <chr>                <dbl> <dbl>          <dbl> <dbl>\n1 (Intercept)              0     0              0     0\n2 movements                0     0              0     0\n3 schools                  0     0              0     0\n4 businesses               0     0              0     0\n5 travel                   0     0              0     0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare the performance between models\nperformance::compare_performance(m1, m2) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 12\n$ Name        <chr> \"m1\", \"m2\"\n$ Model       <chr> \"lm\", \"lm\"\n$ AIC         <dbl> 25279.52, 24099.63\n$ AIC_wt      <dbl> 6.171416e-257, 1.000000e+00\n$ AICc        <dbl> 25279.59, 24099.70\n$ AICc_wt     <dbl> 6.178321e-257, 1.000000e+00\n$ BIC         <dbl> 25310.00, 24129.93\n$ BIC_wt      <dbl> 5.627208e-257, 1.000000e+00\n$ R2          <dbl> 0.2294056, 0.1794016\n$ R2_adjusted <dbl> 0.2268000, 0.1765399\n$ RMSE        <dbl> 10052.12, 8398.11\n$ Sigma       <dbl> 10073.343, 8416.395\n```\n\n\n:::\n:::\n\n\nIf you look at `R2 (adj.)` you might feel a sense of disappointment. How does the model explain less variance? If we consider `AIC`, `BIC` and `RMSE`, we improved the model because their values are lower for `m2`. However, it seems that the outliers affected `R2`, which means they inflated this model indicator. In other words, our regression explains less than we hoped for. However, we can be more confident that the predictions of the new model will be more accurate.\n\nIf we inspect the estimates more closely, we also notice that `movements` (where we removed outliers) and `travel` are not significant anymore (i.e. `p.m2 > 0.05`). We should remove these from our model since they do not help explain the variance of `new_cases`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(new_cases ~ schools + businesses,\n         data = m1_no_outliers)\n\nparameters::model_parameters(m3) |>\n  as_tibble() |>\n  select(Parameter, Coefficient, p) |>\n  mutate(across(where(is.numeric), \\(x) round(0, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  Parameter   Coefficient     p\n  <chr>             <dbl> <dbl>\n1 (Intercept)           0     0\n2 schools               0     0\n3 businesses            0     0\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance::model_performance(m3) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1\nColumns: 7\n$ AIC         <dbl> 24098.21\n$ AICc        <dbl> 24098.24\n$ BIC         <dbl> 24118.41\n$ R2          <dbl> 0.1775628\n$ R2_adjusted <dbl> 0.1761312\n$ RMSE        <dbl> 8407.515\n$ Sigma       <dbl> 8418.483\n```\n\n\n:::\n:::\n\n\nSimilar to before, after removing the insignificant predictors, we end up with an equally good model (in terms of $adjusted\\ R^2$, but we need fewer variables to explain the same amount of variance in `new_cases`. Our final model `m3` is a parsimonious and less complex model.\n\n### Standardised beta ($\\beta$) vs. unstandardised beta ($B$) {#sec-standardised-beta-vs-unstandardised-beta}\n\nIn multiple regressions, we often use variables that are measured in different ways and which use different measurement units, e.g. currency, age, etc. Thus, it is sometimes fairly difficult to interpret regression coefficients without standardising the measurement units. Standardised scores (also called *z-scores*) imply that each variable has a distribution where the mean equals `0` and the standard deviation equals `1`. By transforming our variables to z-scores, they become 'unit free' [@cohen2014applied] (p. 25) and are easier to interpret. Here is an example with a simplified dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create some data\ndata <- tibble(x = c(1, 2, 3, 4))\n\n# Compute z-scores\ndata <-\n  data |>\n  mutate(x_scaled = scale(x))\n\n# Compare the mean and sd for each variable\n# and put it into a nice table\ntibble(\n  variable = c(\"x\", \"x_scaled\"),\n  mean = c(mean(data$x), mean(data$x_scaled)),\n  sd = c(sd(data$x), sd(data$x_scaled))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  variable  mean    sd\n  <chr>    <dbl> <dbl>\n1 x          2.5  1.29\n2 x_scaled   0    1   \n```\n\n\n:::\n:::\n\n\nIf you feel that my choice of values has likely affected the outcome, please feel free to change the values for `x` in this code chunk to whatever you like. The results for `x_scaled` will always remain the same. There is something else that remains the same: the actual distribution. Because we are only rescaling our data, we are not affecting the differences between these scores. We can show this in a scatterplot and by running a correlation. Both will show that these variables are perfectly correlated. Therefore, our transformations did not affect the relative relationship of values to each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |>\n  ggplot(aes(x = x,\n             y = x_scaled)) +\n  geom_point() +\n  geom_smooth(method = \"lm\",\n              formula = y ~ x,\n              se = FALSE)\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/scaled-unscaled-data-comparison-1.png){fig-alt='This line plot shows the variable \\'x\\' plotted against its scaled version \\'x_scaled\\', displaying a linear relationship. Each point on the line represents an increase in \\'x\\' with a corresponding increase in \\'x_scaled\\', indicating consistent scaling.' width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrelation::correlation(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 | Parameter2 |    r |       95% CI | t(2) |         p\n----------------------------------------------------------------\nx          |   x_scaled | 1.00 | [1.00, 1.00] |  Inf | < .001***\n\np-value adjustment method: Holm (1979)\nObservations: 4\n```\n\n\n:::\n:::\n\n\nIt is not a bad idea for regressions to report both unstandardised ($B$) and standardised ($\\beta$) values for each predictor, because comparing predictors based on standardised $\\beta$s only could lead to misleading interpretations as the differences in coefficients could not relate to the true effect size but differences in standard deviations. Let's look at an example where this issues becomes more evident. Consider the `swm` dataset which contains the variables `salary`, `work_experience` and `mindfulness`. We are curious to know to which extend `work_experience` and `mindfulness` predict `salary`. In a first step, we run the model with scaled variables which returns standardised $\\beta$ coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Multiple regression model with scaled variables\nmodel <- lm(scale(salary) ~ scale(work_experience) + scale(mindfulness),\n            data = swm)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = scale(salary) ~ scale(work_experience) + scale(mindfulness), \n    data = swm)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72465 -0.36714  0.05038  0.41489  2.05082 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            -3.128e-16  6.244e-02   0.000        1    \nscale(work_experience)  6.451e-01  6.337e-02  10.179  < 2e-16 ***\nscale(mindfulness)      5.475e-01  6.337e-02   8.639 1.16e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6244 on 97 degrees of freedom\nMultiple R-squared:  0.6179,\tAdjusted R-squared:  0.6101 \nF-statistic: 78.45 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nConsidering the outcome, it would seem that both variables are good predictors for `salary` and their `Estimate`s are almost the same. Thus, one could be fooled into thinking that they are equally important. We can repeat the analysis but obtain unstandardised $\\beta$s.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Multiple regression model with scaled variables\nmodel <- lm(salary ~ work_experience + mindfulness,\n            data = swm)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = salary ~ work_experience + mindfulness, data = swm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-29.739  -6.331   0.869   7.154  35.363 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     -20.15294   12.56370  -1.604    0.112    \nwork_experience   2.42379    0.23811  10.179  < 2e-16 ***\nmindfulness       0.49650    0.05747   8.639 1.16e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.77 on 97 degrees of freedom\nMultiple R-squared:  0.6179,\tAdjusted R-squared:  0.6101 \nF-statistic: 78.45 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThis time the `Estimate`s are quite different from each other, i.e. $work\\_experience = 2.42$ and $mindfulness = 0.50$. Considering these results it becomes clear that `work_experience` has a much stronger impact on `salary` than `mindfulness`. We can further confirm this by graphing the regression lines for each variable separately.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswm |>\n  # Preparing data for plotting\n  pivot_longer(cols = c(work_experience, mindfulness),\n               values_to = \"value\",\n               names_to = \"variable\") |>\n  \n  # Creating the plot\n  ggplot(aes(x = value,\n             y = salary,\n             col = variable,\n             group = variable)) +\n  geom_point() +\n  geom_smooth(method = \"lm\",\n              formula = y ~ x,\n              se = FALSE,\n              col = \"#3e3c42\") +\n  \n  # Choose custom colours for the dots\n  scale_color_manual(values = c(\"#5c589a\", \"#fc5c5d\")) +\n  ggdist::theme_ggdist()\n```\n\n::: {.cell-output-display}\n![](13_regressions_files/figure-html/visualising-swm-regression-1.png){fig-alt='This scatter plot shows the relationship between \\'mindfulness\\' (blue points), \\'work_experience\\' (red points) with regards to \\'salary\\'. Two trend lines indicate distinct patterns for each variable’s impact on salary.' width=672}\n:::\n:::\n\n\nWe can see that while `work_experience` is more centralised around its regression line, `mindfulness` is much more spread out across the x-axis. In other words, the standard deviation of `mindfulness` is much larger.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Comparing the standard deviation\nswm |>\n  summarise(work_xp_sd = sd(work_experience),\n            mindfulness_sd = sd(mindfulness)\n            )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  work_xp_sd mindfulness_sd\n       <dbl>          <dbl>\n1       4.59           19.0\n```\n\n\n:::\n:::\n\n\nWe can also see that the slope of the regression line is different, indicating that a small change in `work_experience` has a much greater impact on `salary` than `mindfulness`. Thus, we need to be very careful when interpreting standardised coefficients. Of course, when in doubt (or simply confused), a data visualisation like this one can provide more certainty about the relationship of variables and their strength.\n\nUnfortunately, this is not the end of the story because 'standardisation' can mean different things. We can generate standardised $\\beta$ after the fact (post-hoc) or decide to 'refit' our regression with standardised predictors, i.e. before we run the regression. Both options are appropriate, but the scores will differ slightly. However, the main idea remains the same: We want to interpret different regression coefficients based on their standard deviations and not their absolute scores. In *R*, many different packages offer standardised estimates. One package I particularly recommend is `parameters`. It provides various options for returning our estimates from a linear model by specifying the `standardize` argument (see [detailed documentation](https://easystats.github.io/parameters/reference/model_parameters.default.html \"detailed documentation\"){target=\"blank\"}). Of course, you can also opt to scale the variables by hand, using the `scale()` function, as we did in the previous examples. All three approaches are shown in the following code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scaling 'by hand'\nm3_scaled <- lm(scale(new_cases) ~\n                  scale(schools) +\n                  scale(businesses),\n                data = m1_no_outliers)\n\nparameters::model_parameters(m3_scaled)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Coefficient |   SE |        95% CI |  t(1149) |      p\n--------------------------------------------------------------------\n(Intercept) |    2.00e-15 | 0.03 | [-0.05, 0.05] | 7.49e-14 | > .999\nschools     |        0.29 | 0.03 | [ 0.23, 0.34] |     9.90 | < .001\nbusinesses  |        0.21 | 0.03 | [ 0.16, 0.27] |     7.38 | < .001\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nUncertainty intervals (equal-tailed) and p-values (two-tailed)\n  computed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scaling using 'parameters' package with refit\n# This is equivalent to scaling 'by hand'\nparameters::model_parameters(m3, standardize = \"refit\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Coefficient |   SE |        95% CI |   t(1149) |      p\n---------------------------------------------------------------------\n(Intercept) |   -4.99e-15 | 0.03 | [-0.05, 0.05] | -1.87e-13 | > .999\nschools     |        0.29 | 0.03 | [ 0.23, 0.34] |      9.90 | < .001\nbusinesses  |        0.21 | 0.03 | [ 0.16, 0.27] |      7.38 | < .001\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nUncertainty intervals (equal-tailed) and p-values (two-tailed)\n  computed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scaling using `parameters` package without refitting the model\nparameters::model_parameters(m3, standardize = \"posthoc\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Std. Coef. |   SE |         95% CI | t(1149) |      p\n-------------------------------------------------------------------\n(Intercept) |       0.00 | 0.00 | [ 0.00,  0.00] |   -2.41 | 0.016 \nschools     |       0.29 | 0.03 | [ 0.23,  0.34] |    9.90 | < .001\nbusinesses  |       0.21 | 0.03 | [ 0.16,  0.27] |    7.38 | < .001\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nUncertainty intervals (equal-tailed) and p-values (two-tailed)\n  computed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n\nI prefer to standardise using the `parameters` package because it makes my life easier, and I need to write less code. I can also easily compare results before scaling my variables. The choice is yours, of course. Also, I tend to use `standardize = refit` in most regressions, since it is more in line with what most Social Scientists seem to report in their publications.\n\n### Multicollinearity: The dilemma of highly correlated independent variables {#sec-multicollinearity}\n\nWe finished fitting our model, and we are likely exhausted but also happy that we accomplished something. However, we are not yet done with our analysis. One of the essential post-tests for multiple regressions is a test for *multicollinearity* or sometimes referred to as *collinearity*. The phenomenon of multicollinearity defines a situation in which some of our independent variables can be explained by other independent variables in our regression model. In other words, there exists a substantial correlation (a linear relationship) between two or more independent variables. However, it is crucial to not confuse this with correlations between a dependent variable and independent variables. Remember, a regression reflects the linear relationship between the predictor variables and the outcome variable. As such, we do hope to find a correlation between these variables, just not among the independent variables.\n\nIf we have evidence that multicollinearity exists in our data, we face some problems [@cohen2014applied; @field2013discovering; @sage-methods2004dbw]:\n\n-   *Unstable regression Coefficients*: We cannot trust our regression coefficients, i.e. our estimates ($\\beta$), because the standard errors could be inflated and therefore affect statistical significance.\n\n-   *Ambiguity in variable importance*: Since two independent variables can explain the same variance, it is unclear which one is important since both can be easily interchanged without affecting the model much.\n\n-   *Challenges in hypothesis testing*: Due to inflated standard errors and unstable estimates, it can be challenging to conduct reliable hypothesis tests, leading to potential confusion about the importance of predictors.\n\n-   *Underestimation of model variance*: We likely underestimate the variance our model can explain, i.e. our $R^2$.\n\n-   *Increased Type II errors*: We produce more Type II errors, i.e. we likely reject significant predictors due to statistical insignificance because of the potentially inflated standard errors.\n\nThe *Variance Inflation Factor (VIF)* and its little sibling *Tolerance* are methods to identify issues of multicollinearity. Compared to detecting outliers, it is very simple to compute these indicators and surprisingly uncomplicated to interpret them. The package `performance` offers a simple function called `check_collinearity()` which provides both. The tolerance can be calculated from the VIF as $tolerance = \\frac{1}{VIF}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_collinearity(m3) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 8\n$ Term              <chr> \"schools\", \"businesses\"\n$ VIF               <dbl> 1.181968, 1.181968\n$ VIF_CI_low        <dbl> 1.118281, 1.118281\n$ VIF_CI_high       <dbl> 1.279947, 1.279947\n$ SE_factor         <dbl> 1.087184, 1.087184\n$ Tolerance         <dbl> 0.8460466, 0.8460466\n$ Tolerance_CI_low  <dbl> 0.7812822, 0.7812822\n$ Tolerance_CI_high <dbl> 0.8942299, 0.8942299\n```\n\n\n:::\n:::\n\n\nAs the output already indicates, there is a `Low Correlation` between our independent variables. So, good news for us. In terms of interpretations, we find the following benchmarks as recommendations to determine multicollinearity [@field2013discovering] :\n\n-   `VIF > 10`: Evidence for multicollinearity\n\n-   `mean(VIF) > 1`: If the mean of all VIFs lies substantially above `1`, multicollinearity might be an issue.\n\n-   `Tolerance < 0.1`: Multicollinearity is a severe concern. This is the same condition as `VIF > 10`.\n\n-   `Tolerance < 0.2`: Multicollinearity could be a concern. This is the same condition as `VIF > 5`.\n\nHowever, @cohen2014applied warns to not rely on these indicators alone. There is sufficient evidence that lower VIF scores could also cause issues. Thus, it is always important to still investigate relationships of independent variables statistically (e.g. correlation) and visually (e.g. scatterplots). For example, outliers can often be a cause for too high or too low VIFs. In short, the simplicity in the computation of these indicators should not be mistaken as a convenient shortcut.\n\nSometimes, the errors (or residuals) in a regression model can be closely related to each other as well, which is called *autocorrelation*. Imagine if the mistakes you make when predicting someone’s salary were similar every time - maybe you always underestimate how much someone earns after they reach a certain level or work experience. This pattern can be a problem because regression analysis assumes that these errors should be random and independent from one another. When they are not, it can make our results unreliable, meaning we cannot trust whether our findings are accurate. The *Durbin-Watson Test* offers an equally easy way to detect autocorrelation among residuals. We can use the `car` package and the function `durbinWatsonTest()` to retrieve the relevant information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::durbinWatsonTest(m3) |>\n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  statistic p.value autocorrelation method             alternative\n      <dbl>   <dbl>           <dbl> <chr>              <chr>      \n1     0.135       0           0.930 Durbin-Watson Test two.sided  \n```\n\n\n:::\n:::\n\n\nThe `statistic` of the Durbin-Watson Test can range from 0 to 4, where 2 indicates no correlation. Luckily for us, we do not have to guess whether the difference from our computation is significantly different from 2 because we also get the `p.value` for such test. In our case, our model suffers from strong correlation of error terms because $p.value < 0.05$.\n\nIf we wanted to remedy autocorrelation (and to some extend multicollinearity as well), we could consider, for example:\n\n-   Revisiting the regression model and potentially dropping those variables that measure the same or similar underlying factors [@cohen2014applied].\n\n-   We could collect more data because a larger dataset will always increase the precision of the regression coefficients [@cohen2014applied].\n\n-   Use different modelling techniques [@cohen2014applied] which can resolve such issues, for example, using generalised least squares (GLS) models and transform some variables of concern [@sage-methods2004dbw].\n\nThe cause for autocorrelation is often rooted in either *'clustered data'* or a *'serial dependency'* [@cohen2014applied]. In our dataset, both could apply. First, we have data that was collected over time, which could lead to wrong standard errors if not accounted for. Second, we have data from two different countries (`United Kingdom` and `Germany`). Thus, our data might be clustered.\n\nTo remove serial dependency effects, we would have to transform data and account for the correlation across time. Such a technique is shown in @cohen2014applied (p.149). Furthermore, to counteract the issue of clustered data, we need to use multilevel regression models, also known as hierarchical regressions, which we will cover in the next chapter.\n\n## Hierarchical regression {#sec-hierarchical-regression}\n\nAdding independent variables to a regression model often happens in a stepwise approach, i.e. we do not add all independent variables at once. Instead, we might first add the essential variables (based on prior research), run the regression, and then examine the results. After that, we add more variables that could explain our dependent variable and rerun the regression. This results in two models which we can compare and identify improvements.\n\nIn hierarchical regressions, we most frequently distinguish three types of independent variables, which also reflect the order in which we add variables to a multiple regression:\n\n1.  *Control variables*: These are independent variables that might affect the dependent variable somehow, and we want to make sure its effects are accounted for. Control variables tend to be not the primary focus of a study but ensure that other independent variables (the main effects) are not spurious. Control variables are added first to a regression.\n\n2.  *Main effects variables*: These are the independent variables that the researcher expects will predict the dependent variable best. Main effects variables are added after any control variables.\n\n3.  *Moderating variables*: These are variables that attenuate the strength of the relationship between independent and dependent variables. They are also referred to as *interactions* or *interaction terms.* Moderating variables are added last, i.e. after main effects variables and control variables.\n\nIn the field of Social Sciences, it is rare not to find control variables and/or moderators in multiple regressions because the social phenomena we tend to investigate are usually affected by other factors as well. Classic control variables or moderators are socio-demographic variables, such as age and gender. The following two chapters cover control variables and moderation effects separately from each other. However, it is not unusual to find both types of variables in the same regression model. Thus, they are not mutually exclusive approaches but simply different types of independent variables.\n\n### Regressions with control variables {#sec-regressions-with-control-variables}\n\nHierarchical regression implies that we add variables step-by-step, or as some call it, *'block-wise'*. Each block represents a group of variables. Control variables tend to be the first block of variables added to a regression model. However, there are many other ways to perform multiple regression, for example, starting with all variables and removing those that are not significant, which @cohen2014applied calls a 'tear-down' approach (p. 158). As the title indicates, we take less of an exploratory approach to our analysis because we define the hierarchy, i.e. the order, in which we enter variables. In the Social Sciences, this is often the preferred method, so I cover it in greater detail.\n\nHowever, I should probably explain what the purpose of entering variables in a stepwise approach is. As we discussed in the previous chapter, we sometimes face issues of multicollinearity, which makes it difficult to understand which variables are more important than others in our model. Therefore, we can decide to enter variables that we want to control first and then create another model containing all variables. The procedure is relatively straightforward for our research focus when predicting `new_cases` of COVID-19:\n\n1.  Create a model `m1` (or whatever name you want to give it) containing the dependent variable `new_cases` and a control variable, for example `country`.\n2.  Inspect the results of this model and note down the performance measures.\n3.  Create another model `m2` and include the control variable `country` and all other independent variables of interest, i.e. `schools`, and `businesses`.\n4.  Inspect the results of this model and note down the performance measures.\n5.  Compare models `m1` and `m2` to see whether they are significantly different from each other. We can use `anova()` to perform this step.\n\nLet's put these steps into action and start with formulating our first model. I choose `country` as a control variable because we have sufficient evidence that clustered data could be a reason for the high autocorrelation of residuals we found in @sec-multicollinearity. For all computations in this section, we use the original dataset, i.e. `covid_uk_ger`, because we changed the model and therefore would have to revisit outliers from scratch, which we shall skip. We also have to remove observations with missing data to allow comparisons of models and ensure they have the same degrees of freedom (i.e. the same number of observations). So, we begin by selecting our variables of interest and then remove missing data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhr_data <-\n  covid_uk_ger |>\n  select(new_cases, country, schools, businesses) |>\n  droplevels() |>\n  na.omit()\n```\n:::\n\n\nWe have to recode factors into so-called [dummy variables](https://methods.sagepub.com/reference/the-sage-encyclopedia-of-educational-research-measurement-and-evaluation/i7682.xml?fromsearch=true \"dummy variables\"){target=\"blank\"} or indicator variables. Dummy variables represent categories as `0`s (i.e. `FALSE` for this observation) and `1`s (`TRUE` for this observation). The good news is, the `lm()` function will do this automatically for us. If you want to inspect the coding ex-ante, you can use the function `contrasts().`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(hr_data$country)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               United Kingdom\nGermany                     0\nUnited Kingdom              1\n```\n\n\n:::\n:::\n\n\nThe column reflects the coding and the rows represent the levels of our factor. If we had more levels, we will find that the coding will always be the number of levels minus 1. This is a common mistake that novice analysts easily make. You might think you need to have a dummy variable for `Germany` (i.e. 0 and 1) and a dummy variable for `United Kingdom` (i.e. 0 and 1). However, all you really need is one variable, which tells us whether the `country` is the `United Kingdom` (i.e. 1) or not (i.e. 0).\n\nIf our control variable has more than two levels, for example, by adding `Italy`, the dummy coding will change to the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhr_uk_ger_ita <-\n  covid |>\n  filter(country == \"United Kingdom\" |\n           country == \"Germany\" |\n           country == \"Italy\") |>\n  droplevels()\n\ncontrasts(hr_uk_ger_ita$country)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Italy United Kingdom\nGermany            0              0\nItaly              1              0\nUnited Kingdom     0              1\n```\n\n\n:::\n:::\n\n\nWith this new dataset of three countries, our regression would include more control variables because we create a new control variable for each level of the factor (minus one level!).\n\nReturning to our hierarchical regression, we can build our first model, i.e. `m1`, which only contains our control variable `country`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(formula = new_cases ~ country,\n         data = hr_data)\n\nparameters::model_parameters(m1, standardize = \"refit\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter                | Coefficient |   SE |         95% CI\n--------------------------------------------------------------\n(Intercept)              |       -0.18 | 0.04 | [-0.26, -0.10]\ncountry [United Kingdom] |        0.37 | 0.06 | [ 0.25,  0.48]\n\nParameter                | t(1186) |      p\n-------------------------------------------\n(Intercept)              |   -4.53 | < .001\ncountry [United Kingdom] |    6.40 | < .001\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nUncertainty intervals (equal-tailed) and p-values (two-tailed)\n  computed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::model_performance(m1) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1\nColumns: 7\n$ AIC         <dbl> 25542.72\n$ AICc        <dbl> 25542.74\n$ BIC         <dbl> 25557.96\n$ R2          <dbl> 0.03341824\n$ R2_adjusted <dbl> 0.03260325\n$ RMSE        <dbl> 11258.08\n$ Sigma       <dbl> 11267.56\n```\n\n\n:::\n:::\n\n\nOur control variable turns out to be significant for our model, but it explains only a small proportion of the variance in `new_cases`. If you are testing hypotheses, you would consider this a good result because you do not want your control variables to explain too much variance. At the same time, it is a significant variable and should be retained in our model. Let's construct our next model, `m1`, by adding the main effects variables and comparing our models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(formula = new_cases ~\n           schools +\n           businesses +\n           country,\n         data = hr_data)\n\nparameters::compare_parameters(m1, m2, standardize = \"refit\") |>\n  as_tibble() |>\n  select(Parameter, Coefficient.m1, p.m1, Coefficient.m2, p.m2) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  Parameter                Coefficient.m1  p.m1 Coefficient.m2  p.m2\n  <chr>                             <dbl> <dbl>          <dbl> <dbl>\n1 (Intercept)                      -0.183     0         -0.235     0\n2 country [United Kingdom]          0.365     0          0.469     0\n3 schools                          NA        NA          0.328     0\n4 businesses                       NA        NA          0.246     0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::compare_performance(m1, m2) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 12\n$ Name        <chr> \"m1\", \"m2\"\n$ Model       <chr> \"lm\", \"lm\"\n$ AIC         <dbl> 25542.72, 25234.10\n$ AIC_wt      <dbl> 9.613761e-68, 1.000000e+00\n$ AICc        <dbl> 25542.74, 25234.15\n$ AICc_wt     <dbl> 9.761451e-68, 1.000000e+00\n$ BIC         <dbl> 25557.96, 25259.50\n$ BIC_wt      <dbl> 1.545684e-65, 1.000000e+00\n$ R2          <dbl> 0.03341824, 0.25706142\n$ R2_adjusted <dbl> 0.03260325, 0.25517897\n$ RMSE        <dbl> 11258.076, 9870.095\n$ Sigma       <dbl> 11267.564, 9886.753\n```\n\n\n:::\n:::\n\n\nAfter adding all our variables, $adjusted\\ R^2$ went up from `0.033` to `0.255`. While this might seem like a considerably improvement, we have to perform a statistical test to compare the two models. This leads us back to comparing groups, and in many ways, this is what we do here by using the function `anova()`, but we compare models based on the residual sum of squares, i.e. the amount of error the models produce. Thus, if the ANOVA returns a significant result, `m1` shows a significantly reduced residual sum of squares compared to `m2`. Therefore, `m2` would be the better model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1, m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: new_cases ~ country\nModel 2: new_cases ~ schools + businesses + country\n  Res.Df        RSS Df  Sum of Sq      F    Pr(>F)    \n1   1186 1.5057e+11                                   \n2   1184 1.1573e+11  2 3.4839e+10 178.21 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe results confirm that our model significantly improved. You might argue that this is not surprising because we added those variables which already worked in the final model of @sec-multicollinearity. However, the important takeaway is that our control variable `country` helps us explain more variance in `new_cases`. Comparing the model with and without the control variable, we would find that the $adjusted\\ R^2$ improves our model by about 25%. As such, it is worth keeping it as part of our final regression model. Here is evidence of this improvement:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- lm(formula = new_cases ~\n           schools +\n           businesses,\n         data = hr_data)\n\nperformance::compare_performance(m0, m2) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 12\n$ Name        <chr> \"m0\", \"m2\"\n$ Model       <chr> \"lm\", \"lm\"\n$ AIC         <dbl> 25309.15, 25234.10\n$ AIC_wt      <dbl> 5.057329e-17, 1.000000e+00\n$ AICc        <dbl> 25309.18, 25234.15\n$ AICc_wt     <dbl> 5.10037e-17, 1.00000e+00\n$ BIC         <dbl> 25329.47, 25259.50\n$ BIC_wt      <dbl> 6.412612e-16, 1.000000e+00\n$ R2          <dbl> 0.2072824, 0.2570614\n$ R2_adjusted <dbl> 0.2059444, 0.2551790\n$ RMSE        <dbl> 10195.397, 9870.095\n$ Sigma       <dbl> 10208.294, 9886.753\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m0, m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: new_cases ~ schools + businesses\nModel 2: new_cases ~ schools + businesses + country\n  Res.Df        RSS Df  Sum of Sq      F    Pr(>F)    \n1   1185 1.2349e+11                                   \n2   1184 1.1573e+11  1 7754483300 79.332 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThere are many more combinations of models we could test. For example, instead of specifying two models (`m1`, `m2`), we could also add independent variables one at a time and compare the resulting models to a baseline model (`m0`). Thus, we end up with more models to compare, for example:\n\n::: {#four-hierarchical-regressions-nested}\nm1 \\<- lm(formula = new_cases \\~ country, data = hr_data)\n\nm2 \\<- lm(formula = new_cases \\~ country + schools, data = hr_data)\n\nm3 \\<- lm(formula = new_cases \\~ country + schools + businesses, data = hr_data)\n:::\n\nAll these decisions have to be guided by the purpose of your research and whether you explore your data or have pre-defined hypotheses. However, the steps remain the same in terms of computation in *R*.\n\n### Moderated regression {#sec-moderated-regression}\n\nWhile regressions with control variables help us decide whether to include or exclude variables by controlling for another variable, moderation models imply that we expect a certain interaction between an independent variable and a so-called *moderator*. A moderator also enters the equation on the right-hand side and therefore constitutes an independent variable, but it is usually entered after control variables and main effects variables.\n\nIn our quest to find a model that predicts new COVID cases, let's assume that country is not a control variable but a moderating one. We could suspect that the measures for `businesses` and `schools` were significantly differently implemented in each country. Therefore, the strength of the relationship between `businesses`/`schools` and `new_cases` varies depending on the country. In other words, we could assume that measures showed different effectiveness in each of the countries.\n\nWhen performing a moderation regression, we assume that the relationship between independent variables and the dependent variable differs based on a third variable, in our case, `country`. Thus, if we visualise the idea of moderation, we would plot the data against each other for each country separately and fit two (instead of one) regression lines by defining the colours of each group with `col = country`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plotting the interaction between schools and country\nhr_data |>\n  ggplot(aes(x = schools,\n             y = new_cases,\n             col = country)) +\n  geom_jitter(width = 5,\n              size = 0.5,\n              alpha = 0.5) +\n  stat_smooth(method = \"lm\",\n              formula = y ~ x,\n              se = FALSE)\n```\n\n::: {.cell-output-display}\n![Plotting moderation effects for `schools`.](13_regressions_files/figure-html/fig-plotting-moderation-effects-schools-1.png){#fig-plotting-moderation-effects-schools fig-alt='This scatter plot shows the relationship between the school measures taken (x-axis) and new COVID-19 cases (y-axis) in Germany and the United Kingdom. Germany’s data points and trend line are shown in red, while the United Kingdom’s are in teal. The trend lines indicate a stronger positive correlation between school measures taken and new cases in the United Kingdom compared to Germany.' width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plotting the interaction between schools and country\nhr_data |>\n  ggplot(aes(x = businesses,\n             y = new_cases,\n             col = country)) +\n  geom_jitter(width = 5,\n              size = 0.5,\n              alpha = 0.5) +\n  geom_smooth(method = \"lm\",\n              formula = y ~ x,\n              se = FALSE)\n```\n\n::: {.cell-output-display}\n![Plotting moderation effects for `business`.](13_regressions_files/figure-html/plotting-moderation-effects-businesses-1.png){fig-alt='This scatter plot shows the relationship between the amount of business measures taken (x-axis) and new COVID-19 cases (y-axis) in Germany and the United Kingdom. Germany’s data points and trend line are shown in red, while the United Kingdom’s are in teal. The trend lines indicate a stronger positive correlation between business measures taken and new cases in the United Kingdom compared to Germany.' width=672}\n:::\n:::\n\n\nThere are three interesting insights we can gain from these plots:\n\n1.  In terms of `business` measures, the `United Kingdom` seems to have more observations at the lower end, i.e. taking less protective measures than Germany. In contrast, for `schools`, it is the opposite.\n2.  For `schools`, the UK reports more frequently higher numbers of `new_cases` even if measures taken are high, which results in a steeper regression line.\n3.  However, for `businesses`, the `United Kingdom` had barely any `new_cases` when the measures were high, but Germany still reports high numbers of new cases when tight measures were taken.\n\nGiven the difference in the slope of the regression lines, we have to assume that the $\\beta$s for `Germany` are quite different from the ones for the `United Kingdom`. It seems that the relationship between `new_cases` and `business`/`schools` can be partially explained by `country`. Therefore, we could include `country` as a moderator and introduce the interaction of these variables with each other into a new model, i.e. `m4`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- lm(formula = new_cases ~\n           schools +\n           businesses +\n           schools * country +  # moderator 1\n           businesses * country, # moderator 2\n         data = hr_data)\n\nparameters::compare_parameters(m0, m4, standardize = \"refit\") |>\n  as_tibble() |>\n  select(Parameter, Coefficient.m0, p.m0, Coefficient.m4, p.m4) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  Parameter                  Coefficient.m0  p.m0 Coefficient.m4  p.m4\n  <chr>                               <dbl> <dbl>          <dbl> <dbl>\n1 (Intercept)                         0         1         -0.229 0    \n2 schools                             0.366     0          0.077 0.104\n3 businesses                          0.168     0          0.183 0    \n4 country [United Kingdom]           NA        NA          0.546 0    \n5 schools × country [United…         NA        NA          0.274 0    \n6 businesses × country [Uni…         NA        NA          0.371 0    \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::compare_performance(m0, m4) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 12\n$ Name        <chr> \"m0\", \"m4\"\n$ Model       <chr> \"lm\", \"lm\"\n$ AIC         <dbl> 25309.15, 25149.91\n$ AIC_wt      <dbl> 2.642292e-35, 1.000000e+00\n$ AICc        <dbl> 25309.18, 25150.00\n$ AICc_wt     <dbl> 2.724264e-35, 1.000000e+00\n$ BIC         <dbl> 25329.47, 25185.47\n$ BIC_wt      <dbl> 5.38669e-32, 1.00000e+00\n$ R2          <dbl> 0.2072824, 0.3102162\n$ R2_adjusted <dbl> 0.2059444, 0.3072984\n$ RMSE        <dbl> 10195.397, 9510.456\n$ Sigma       <dbl> 10208.294, 9534.564\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m0, m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: new_cases ~ schools + businesses\nModel 2: new_cases ~ schools + businesses + schools * country + businesses * \n    country\n  Res.Df        RSS Df  Sum of Sq      F    Pr(>F)    \n1   1185 1.2349e+11                                   \n2   1182 1.0745e+11  3 1.6035e+10 58.795 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe moderation effect is quite strong. Compared to our baseline model `m0`, which only contains `businesses` and `schools` as predictors, our new model `m4` considerably outperforms it with an $adjusted\\ R^2 = 0.307$. Our previous model with country as a control variable achieved an $adjusted\\ R^2 = 0.255$. I would argue this is quite an improvement.\n\nWhile significant moderation effects help us make better predictions with our model, they come with a caveat: Interpreting the relative importance of the main effects becomes considerably more difficult because their impact depends on the level of our moderation variable. As such, you cannot interpret the main effects without considering the moderation variable as well. You might have noticed that our variable `schools` is not significant anymore. However, this does not imply it is not essential because its significance depends on the level of our moderator, i.e. whether we look at `Germany` or the `United Kingdom`.\n\n### Centering predictors: Making $\\beta$s more interpretable {#sec-centering-predictors}\n\nIn @sec-standardised-beta-vs-unstandardised-beta, we covered procedures to standardise $\\beta$ coefficients, which allow us to compare independent variables based on different measurement units or if we want to compare coefficients across multiple models. Whenever we perform a regression with an interaction term, for example, the moderation regression in the previous chapter, we often have to make similar adjustments called *'centering'*.\n\nTo explain why we might need centering, we should look at an example. Let's consider a simple model using the `wvs_nona` dataset. Assume we want to know whether `freedom_of_choice` can predict `satisfaction` with life, moderated by `age`. If we formulate this as a model, we can write the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(formula = satisfaction ~\n              freedom_of_choice +\n              freedom_of_choice * age,\n            data = wvs_nona)\n\nparameters::model_parameters(model) |>\n  as_tibble() |>\n  select(Parameter, Coefficient, t, df_error, p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  Parameter             Coefficient      t df_error        p\n  <chr>                       <dbl>  <dbl>    <int>    <dbl>\n1 (Intercept)              3.42     16.3       8560 1.40e-58\n2 freedom_of_choice        0.409    13.9       8560 1.50e-43\n3 age                      0.00815   1.78      8560 7.57e- 2\n4 freedom_of_choice:age   -0.000635 -0.978     8560 3.28e- 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::model_performance(model) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1\nColumns: 7\n$ AIC         <dbl> 37214.9\n$ AICc        <dbl> 37214.91\n$ BIC         <dbl> 37250.18\n$ R2          <dbl> 0.1291467\n$ R2_adjusted <dbl> 0.1288414\n$ RMSE        <dbl> 2.123849\n$ Sigma       <dbl> 2.124345\n```\n\n\n:::\n:::\n\n\nThe $\\beta$ score of `freedom_of_choice` unfolds the most substantial effect on `satisfaction`, but assumes that `age = 0`. In regressions with interaction terms, the coefficient $\\beta$ of a variable reflects the change in the dependent variables if other variables are set to zero. If this is a logical value for the variables, then no further steps are required. However, if a score of zero on any predictor is not meaningful, it is recommended to engage in centering variables [see @cohen2014applied; @field2013discovering]. In our model, the coefficient of `freedom_of_choice` assumes that `age` is equal to `0`. However, no participant in our sample will have been of age `0`, which renders any interpretation of the $\\beta$ coefficient meaningless. Instead, it is more meaningful to retrieve a $\\beta$ score which is based on the average `age` of people in our sample. This is what centering can achieve.\n\nThere are mainly two very commonly used techniques in the Social Sciences to center variables: *grand mean centering* and *group mean centering*. The difference between these two approaches lies in their reference sample. For group mean centering, we compute means for each group independently and for grand mean centering, we calculate the mean for all observations irrespective of any groupings. Centered scores are almost the same as z-scores, but without using standard deviation as a measurement unit. If we divided centered scores by the standard deviation, we would have computed z-scores. The following formula summarises the computation of centered variables:\n\n::: {#centering-formula align=\"center\"}\n$x_{n_{centered}} = x_n - \\overline{x}$\n:::\n\nIn other words, to achieve a centered variable ($x_{n_{centered}}$), we have to take the original observation ($x_n$) and subtract the mean of the variable ($\\bar{x}$). How we define $\\bar{x}$ determines whether we perform grand mean centering (using the entire dataset) or group mean centering (using subsets of our data, i.e. groups). We already know all the functions needed to compute centered variables. Since the `age` of `0` is not meaningful in our study, we should center this variable around its mean[^13_regressions-5].\n\n[^13_regressions-5]: It is not required to choose the mean as a way to center variables. Any value that is meaningful can be used. However, the mean often tends to be the most meaningful value to perform centering.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grand mean centering\nwvs_nona_c <-\n  wvs_nona |>\n  mutate(age_c = age - mean(age))\n\nwvs_nona_c |>\n  select(age, age_c) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n    age  age_c\n  <dbl>  <dbl>\n1    60  17.9 \n2    40  -2.14\n3    25 -17.1 \n4    71  28.9 \n5    38  -4.14\n6    20 -22.1 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group mean centering by country\nwvs_nona |>\n  group_by(country) |>\n  mutate(age_c = age - mean(age)) |>\n  \n  select(age, age_c) |>\n  sample_n(1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nAdding missing grouping variables: `country`\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n# Groups:   country [6]\n  country   age  age_c\n  <fct>   <dbl>  <dbl>\n1 Bolivia    22 -16.3 \n2 Iran       53  13.5 \n3 Iraq       64  27.4 \n4 Japan      42 -12.8 \n5 Korea      48   2.37\n6 Egypt      35  -4.70\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## The group means used\nwvs_nona |>\n  group_by(country) |>\n  summarise(mean = round(mean(age), 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  country  mean\n  <fct>   <dbl>\n1 Bolivia    38\n2 Iran       39\n3 Iraq       37\n4 Japan      55\n5 Korea      46\n6 Egypt      40\n```\n\n\n:::\n:::\n\n\nThe `mutate()` function is the same for both approaches. However, we used `group_by()` to compute the mean for each `country` and then centered the scores accordingly for group mean centering. Thus, observations from `Australia` will be centered around the mean score of `54`, while observations from `Myanmar` will be centered around the mean value of `40`.\n\nReturning to our investigation, I opted to choose grand mean centering. Now we can use our newly centered variable in the regression to see the impact it had on our $\\beta$s.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_c <- lm(formula = satisfaction ~\n                freedom_of_choice +\n                freedom_of_choice * age_c,\n              data = wvs_nona_c)\n\nparameters::compare_parameters(model, model_c) |>\n  as_tibble() |>\n  select(Parameter, Coefficient.model, p.model,\n         Coefficient.model_c, p.model_c) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  Parameter    Coefficient.model p.model Coefficient.model_c p.model_c\n  <chr>                    <dbl>   <dbl>               <dbl>     <dbl>\n1 (Intercept)              3.42    0                   3.77      0    \n2 freedom of …             0.409   0                   0.382     0    \n3 age                      0.008   0.076              NA        NA    \n4 freedom of …            -0.001   0.328              NA        NA    \n5 age c                   NA      NA                   0.008     0.076\n6 freedom of …            NA      NA                  -0.001     0.328\n```\n\n\n:::\n:::\n\n\nIn contrast to standardising the coefficients, it is not necessary to center all predictors in your dataset. For example, we only centered `age` and not `freedom_of_choice` in our case, because a value of `0` for the latter variable seems plausible. As we can tell from the output, the $\\beta$ for `freedom_of_choice` has changed, but all other coefficients remained the same. In general, grand mean centering has the following effects:\n\n-   centering does not affect the $\\beta$ of the centered variable (i.e. `age`), because we subtract a constant (i.e. the mean) from all observations equally,\n\n-   centering does not affect the interaction term (i.e. `freedom_of_choice * age_c)`, which is also known as the *higher-order predictor*,\n\n-   centering changes the $\\beta$ of the independent variable in the interaction term (also known as *lower-order predictor*), i.e. `freedom_of_choice`,\n\n-   centering does not change $\\beta$s of other variables that are not interacting with a centered variable.\n\n-   centering any of the predictors changes the intercept.\n\nTo conclude, centering plays a crucial role if the interpretation of $\\beta$ coefficients is essential. If this is true, we should center all variables where a value of `0` is not meaningful. However, keep in mind that we do not change the model itself, i.e. we cannot improve the performance of a model by centering certain variables. Consequently, if we are only interested in the performance of our model, centering does not matter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::compare_performance(model, model_c) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 12\n$ Name        <chr> \"model\", \"model_c\"\n$ Model       <chr> \"lm\", \"lm\"\n$ AIC         <dbl> 37214.9, 37214.9\n$ AIC_wt      <dbl> 0.5, 0.5\n$ AICc        <dbl> 37214.91, 37214.91\n$ AICc_wt     <dbl> 0.5, 0.5\n$ BIC         <dbl> 37250.18, 37250.18\n$ BIC_wt      <dbl> 0.5, 0.5\n$ R2          <dbl> 0.1291467, 0.1291467\n$ R2_adjusted <dbl> 0.1288414, 0.1288414\n$ RMSE        <dbl> 2.123849, 2.123849\n$ Sigma       <dbl> 2.124345, 2.124345\n```\n\n\n:::\n:::\n\n\n## Other regression models: Alternatives to OLS {#sec-ols-alternatives}\n\nThis book only covers linear regressions, which are considered *Ordinary Least Squares (OLS) regression* models. These are by far the most frequently used models in the Social Sciences. However, what can we do if the assumptions of OLS models are violated, for example, the relationship of variables looks curved or if our dependent variable is dichotomous and not continuous? In such cases, we might have to consider other types of regression models. There are several different approaches, but we most frequently find one of the following:\n\n-   *Polynomial regressions*, which are used for curvilinear relationships between variables.\n\n-   *Generalised Linear models*, such as *Logistic regressions* (when the predictor is a logical variable) or *Poisson regressions* (when we model count data, i.e. frequencies and contingency tables).\n\nThese are specialised models, and learning them requires a more in-depth knowledge of their mechanics which would go beyond the scope of a book that intends to cover the basics of conducting statistical analysis in *R*. However, @cohen2014applied offers an excellent introduction to both approaches.\n\n## Exercises {#sec-exercises-regressions}\n\nAfter such a long chapter it is time to recap what we learned. Use the code provided to practice modeling and interpreting relationships. Remember, you have to install the `r4np` package first, if you have not done so yet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Option 1:\nlearnr::run_tutorial(\"ex_regressions\", package = \"r4np\")\n```\n:::\n",
    "supporting": [
      "13_regressions_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}