{
  "hash": "fc26bedf095ce42a0f60de279dd2ebb0",
  "result": {
    "engine": "knitr",
    "markdown": "# Correlations {#sec-correlations}\n\n\n\n\n\nSometimes, counting and measuring means, medians, and standard deviations is not enough because they are all based on a single variable. Instead, we might have questions about the relationship between two or more variables. In this section, we will explore how correlations can (and kind of cannot - see @sec-simpsons-paradox) provide insights into the following questions:\n\n-   Do people who eat healthier also feel happier?\n\n-   Are happier people also more satisfied with their life?\n\n-   Is eating healthier related to other health factors, such as life expectancy, blood pressure and overweight/obesity?\n\nThere are many different ways to compute the correlation, and it partially depends on the type of data you want to relate to each other. The *Pearson's correlation* is, by far, the most frequently used correlation technique for normally distributed data. On the other hand, if data is not normally distributed, we can opt for the *Spearman's rank* correlation. One could argue that the relationship between these two correlations is like the mean (Pearson) to the median (Spearman). Both approaches require numeric values to be computed correctly. If our data is ordinal or, worse, dichotomous (like a logical variable), we have to choose different options. @tbl-different-correlations summarises different methods depending on the data type.\n\n\n::: {#tbl-different-correlations .cell tbl-cap='Different ways of computing correlations'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ngvnyyupao\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ngvnyyupao table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ngvnyyupao thead, #ngvnyyupao tbody, #ngvnyyupao tfoot, #ngvnyyupao tr, #ngvnyyupao td, #ngvnyyupao th {\n  border-style: none;\n}\n\n#ngvnyyupao p {\n  margin: 0;\n  padding: 0;\n}\n\n#ngvnyyupao .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ngvnyyupao .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ngvnyyupao .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ngvnyyupao .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 15px;\n  padding-bottom: 16px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ngvnyyupao .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ngvnyyupao .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ngvnyyupao .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ngvnyyupao .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 15px;\n  padding-bottom: 15px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ngvnyyupao .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ngvnyyupao .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ngvnyyupao .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ngvnyyupao .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ngvnyyupao .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ngvnyyupao .gt_row {\n  padding-top: 15px;\n  padding-bottom: 15px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ngvnyyupao .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngvnyyupao .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ngvnyyupao .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ngvnyyupao .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ngvnyyupao .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngvnyyupao .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ngvnyyupao .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngvnyyupao .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ngvnyyupao .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngvnyyupao .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ngvnyyupao .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ngvnyyupao .gt_left {\n  text-align: left;\n}\n\n#ngvnyyupao .gt_center {\n  text-align: center;\n}\n\n#ngvnyyupao .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ngvnyyupao .gt_font_normal {\n  font-weight: normal;\n}\n\n#ngvnyyupao .gt_font_bold {\n  font-weight: bold;\n}\n\n#ngvnyyupao .gt_font_italic {\n  font-style: italic;\n}\n\n#ngvnyyupao .gt_super {\n  font-size: 65%;\n}\n\n#ngvnyyupao .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ngvnyyupao .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ngvnyyupao .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ngvnyyupao .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ngvnyyupao .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ngvnyyupao .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ngvnyyupao .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ngvnyyupao .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ngvnyyupao div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:0px;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:90px;\"/>\n    <col style=\"width:360px;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"correlation\">Correlation</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"used_when\">Used when ...</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"correlation\" class=\"gt_row gt_left\" style=\"font-style: italic;\"><span data-qmd-base64=\"UGVhcnNvbg==\"><span class='gt_from_md'>Pearson</span></span></td>\n<td headers=\"used_when\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Li4uIHZhcmlhYmxlcyBhcmUgbnVtZXJpYyBhbmQgcGFyYW1ldHJpYw==\"><span class='gt_from_md'>… variables are numeric and parametric</span></span></td></tr>\n    <tr><td headers=\"correlation\" class=\"gt_row gt_left\" style=\"font-style: italic;\"><span data-qmd-base64=\"U3BlYXJtYW4=\"><span class='gt_from_md'>Spearman</span></span></td>\n<td headers=\"used_when\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Li4uIHZhcmlhYmxlcyBhcmUgbnVtZXJpYyBhbmQgbm9uLXBhcmFtZXRyaWM=\"><span class='gt_from_md'>… variables are numeric and non-parametric</span></span></td></tr>\n    <tr><td headers=\"correlation\" class=\"gt_row gt_left\" style=\"font-style: italic;\"><span data-qmd-base64=\"UG9seWNob3JpYw==\"><span class='gt_from_md'>Polychoric</span></span></td>\n<td headers=\"used_when\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Li4uIGludmVzdGlnYXRpbmcgdHdvIG9yZGluYWwgdmFyaWFibGVz\"><span class='gt_from_md'>… investigating two ordinal variables</span></span></td></tr>\n    <tr><td headers=\"correlation\" class=\"gt_row gt_left\" style=\"font-style: italic;\"><span data-qmd-base64=\"VGV0cmFjaG9yaWM=\"><span class='gt_from_md'>Tetrachoric</span></span></td>\n<td headers=\"used_when\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Li4uIGJvdGggdmFyaWFibGVzIGFyZSBkaWNob3RvbW91cywgZS5nLiwg4oCYeWVzL25v4oCZLCDigJhUcnVlL0ZhbHNl4oCZLg==\"><span class='gt_from_md'>… both variables are dichotomous, e.g., ‘yes/no’, ‘True/False’.</span></span></td></tr>\n    <tr><td headers=\"correlation\" class=\"gt_row gt_left\" style=\"font-style: italic;\"><span data-qmd-base64=\"UmFuay1iaXNlcmlhbA==\"><span class='gt_from_md'>Rank-biserial</span></span></td>\n<td headers=\"used_when\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Li4uIG9uZSB2YXJpYWJsZSBpcyBkaWNob3RvbW91cyBhbmQgdGhlIG90aGVyIHZhcmlhYmxlIGlzIG9yZGluYWw=\"><span class='gt_from_md'>… one variable is dichotomous and the other variable is ordinal</span></span></td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThere are many more variations of correlations, which you can explore on the [package's website](https://easystats.github.io/correlation/articles/types.html \"website of the package\"){target=\"blank\"} we will use in this chapter: `correlation`. However, we will primarily focus on Pearson and Spearman because they are the most commonly used correlation types in academic publications to understand the relationship between two variables. In addition, we also look at *partial correlations,* which allow us to introduce a third variable into this mix.\n\n## Plotting correlations {#sec-plotting-correlations}\n\nSince correlations only show the relationship between two variables, we can easily put one variable on the x-axis and one on the y-axis, creating a so-called 'scatterplot'. We used two functions to plot scatterplots before, i.e. `geom_point()` and `geom_jitter()`, which we can use to answer our first research questions, i.e. whether people who eat healthier also feel happier. One assumption might be that healthier eating habits contribute to better physical well-being, which in turn enhances happiness. However, a counter-argument could be that diet does not significantly impact happiness levels, as everyone is subject to various life circumstances that influence our mood. Either way, we first need to identify the two variables of interest, which we can find in the `hie_2021` dataset. It contains measures of national health in various areas of England collected in 2021, such as:\n\n-   `happiness`, which measures the average happiness of respondents when asked how they felt the day before on a scale from `0` (not at all) to `10` (completely), and\n\n-   `healthy_eating`, which represents the percentage of adults who report eating five or more portions of fruit and vegetables on a regular day.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhie_2021 |>\n  ggplot(aes(healthy_eating, happiness)) +\n  geom_point() +\n  \n  # Apply a theme without a grid or background\n  see::theme_modern()\n```\n\n::: {.cell-output-display}\n![](10_correlations_files/figure-html/correlation-happiness-healthy-eating-1.png){fig-alt='Scatter plot showing the relationship between happiness and healthy eating. Each point represents an individual observation, with happiness on the y-axis and healthy eating scores on the x-axis. The plot suggests a weak or scattered association between happiness and healthy eating.' width=672}\n:::\n:::\n\n\nThe results from our scatterplot are, well, somewhat random. We can see that in some areas of England people report very high `happiness` scores as well as high levels of `healthy_eating`. However, some regions score high on `happiness` but low regarding `healthy_eating`. Overall, the points look like they are randomly scattered all over our canvas. The only visible pattern we can notice is that there are slightly more scores at the center of this cloud of dots than on its edges.\n\nSince correlations only explain linear relationships, a perfect correlation would be represented by a straight line. Consider the following examples of correlations:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relationship strength and direction of two quantitative variables](10_correlations_files/figure-html/correlation-examples-1.png){fig-alt='Six scatter plots illustrating different strengths and directions of linear relationships, with corresponding correlation coefficients (r) displayed. Positive correlations (r = 1, 0.89, 0.30) are in the top row, showing varying strengths of positive association, from perfect to weak. Negative correlations (r = -0.42, -0.75, -1) are in the bottom row, showing varying strengths of negative association, from weak to perfect.' width=672}\n:::\n:::\n\n\nA correlation can be either positive or negative, and its value (i.e. `r` in case of the Pearson correlation) can range from `-1` to `1`:\n\n-   `-1` defines a perfectly negative correlation,\n\n-   `0` defines no correlation (completely random), and\n\n-   `1` defines a perfectly positive correlation.\n\nIn other words, the further the score is away from `0`, the stronger is the relationship between variables. We also have benchmarks that we can use to assess the strength of a relationship, for example, the one by @cohen1988statistical. The strength of the relationship is also called *effect size.* @tbl-effect-size-cohen shows the relevant benchmarks. Note that effect sizes are always provided as absolute figures. Therefore, `-0.4` would also count as a moderate relationship.\n\n| effect size         | interpretation |\n|---------------------|----------------|\n| r \\< 0.1            | very small     |\n| 0.1 $\\leq$ r \\< 0.3 | small          |\n| 0.3 $\\leq$ r \\< 0.5 | moderate       |\n| r $\\geq$ 0.5        | large          |\n\n: Assessing effect size of relationships according to @cohen1988statistical. {#tbl-effect-size-cohen}\n\n## Computing correlations {#sec-computing-correlations}\n\nIf we compare the plot from our data with the sample plots, we can conclude that the relationship is weak, and therefore the `r` must be close to zero. We can test this with the Pearson correlation using the function `correlation()` from the `correlation` package. By default, it will perform a Pearson correlation, which is only applicable for parametric data. As outlined before, if our data violates the assumptions for parametric tests, we can use Spearman's correlation instead. For the rest of the chapter, we assume that our data is parametric, but I will demonstrate how to compute both in the following code chunk:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(correlation)\n\n# Pearson correlation\nhie_2021 |>\n  select(happiness, healthy_eating) |>\n  correlation()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 |     Parameter2 |    r |        95% CI | t(305) |     p\n-------------------------------------------------------------------\nhappiness  | healthy_eating | 0.07 | [-0.04, 0.18] |   1.24 | 0.215\n\np-value adjustment method: Holm (1979)\nObservations: 307\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spearman correlation\nhie_2021 |>\n  select(happiness, healthy_eating) |>\n  correlation(method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (spearman-method)\n\nParameter1 |     Parameter2 |  rho |        95% CI |        S |     p\n---------------------------------------------------------------------\nhappiness  | healthy_eating | 0.09 | [-0.03, 0.20] | 4.41e+06 | 0.135\n\np-value adjustment method: Holm (1979)\nObservations: 307\n```\n\n\n:::\n:::\n\n\nIndeed, our analysis reveals that the effect size is very small (r = 0.07 \\< 0.1). Therefore, `healthy_eating`, seems to not make us happier. In all fairness, the foods that make us smile are often not fruits and veggies, but other, more guilty, pleasures.\n\nAnother question we posed at the beginning was: Are people who are happier also more satisfied with their life? Our intuition might say 'yes'. A person who consistently feels happy is more likely to assess their overall life positively, because their day-to-day experiences are enjoyable. Let's create another scatterplot to find out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhie_2021 |>\n  ggplot(aes(x = life_satisfaction, y = happiness)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](10_correlations_files/figure-html/happiness-vs-life-satisfaction-1.png){fig-alt='A scatter plot showing the relationship between life satisfaction (x-axis) and happiness (y-axis). The points are scattered positively, suggesting a positive correlation where higher life satisfaction is associated with higher happiness scores, though with some dispersion around the trend.' width=672}\n:::\n:::\n\n\nThe scatterplot shows a somewhat positive trend which suggests that we are right: Higher `happiness` is linked to higher `life_satisfaction`. Often, it can be tough to see the trend. To improve our plot, we can use the function `geom_smooth()`, which can help us draw a straight line that best fits our data points. We need to set the `method` for drawing the line to `lm`, which stands for *linear model*. Remember, correlations assume a linear relationship between two variables, i.e. we model a linear relationship in our scatterplot. As mentioned before, the stronger the relationship the closer each dot in the plot will be to the red line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhie_2021 |>\n  ggplot(aes(x = life_satisfaction, y = happiness)) +\n  geom_point() +\n  geom_smooth(method = \"lm\",\n              formula = y ~ x,\n              se = FALSE,\n              col = \"red\")\n```\n\n::: {.cell-output-display}\n![](10_correlations_files/figure-html/happiness-vs-life-satisfaction-regression-line-1.png){fig-alt='A scatter plot illustrating the relationship between life satisfaction (x-axis) and happiness (y-axis), with a red trend line indicating a positive linear correlation between the two variables. Higher life satisfaction generally corresponds to higher happiness.' width=672}\n:::\n:::\n\n\nTo find a definitive answer to this research question we can compute the correlation for both variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhie_2021 |>\n  select(life_satisfaction, happiness) |>\n  correlation()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1        | Parameter2 |    r |       95% CI | t(305) |         p\n-------------------------------------------------------------------------\nlife_satisfaction |  happiness | 0.67 | [0.60, 0.73] |  15.73 | < .001***\n\np-value adjustment method: Holm (1979)\nObservations: 307\n```\n\n\n:::\n:::\n\n\nWith an `r` of `0.67`, we did not only find a positive relationship, but one that is considered *large*, according to Cohen (1988).\n\n## Significance: A way to help you judge your findings {#sec-significance}\n\nOne of the most common pitfalls of novice statisticians is the interpretation of what counts as significant and not significant. Most basic tests offer a *p value,* which stands for *probability value*. I have referred to this value multiple times in this book already, but did not thoroughly explain why it is important.\n\nTo understand p-values and significance, we need to briefly discuss *hypotheses*. A hypothesis is an assumption we make about the data, such as whether `healthy_eating` leads to more `happiness` (as in @sec-computing-correlations). In contrast, the null hypothesis is a special type of hypothesis that assumes that no effect or relationship exists between variables, i.e. the opposite of what we are testing. When you read that a hypothesis has been “rejected” or “accepted,” it is often the null hypothesis being tested. The p-value helps determine whether we should reject or retain the null hypothesis based on the data.\n\nThe `p`-value can range from 1 (for 100%) to 0 (for 0%) and helps us assess whether to accept or reject the null hypothesis:\n\n-   $p = 1$, there is a 100% probability that the result is due to pure chance, supporting (accepting) the null hypothesis.\n\n-   $p = 0$, there is a 0% probability that the result is due to pure chance, suggesting that the null hypothesis has to be rejected.\n\nTechnically, we would not find that `p` is ever truly zero and instead denote very small `p`-values with `p < 0.01` or even `p < 0.001`, indicating that our null hypothesis is unlikely to be true.\n\nThere are also commonly considered and accepted thresholds for the `p`-value:\n\n-   $p > 0.05$, the result is not significant.\n\n-   $p \\leq 0.05$, the result is significant, i.e. there is less than a 5% chance that the null hypothesis should have been accepted.\n\n-   $p \\leq 0.01$, the result is highly significant.\n\nMost frequently, confusion about the p-value emerges because we test FOR the null hypothesis and not what we are actually interested in. Returning to our example of eating healthy and its impact on happiness, we would first formulate our hypothesis and the null hypothesis:\n\n-   Hypothesis ($H_1$): Healthy eating and happiness are significantly positively related to each other.\n\n-   Null Hypothesis ($H_0$): There is no significant relationship between healthy eating and happiness.\n\nBased on our research question, we hope to accept our hypothesis and, therefore, reject the null hypothesis. Hardly ever will you find that researchers are interested in not finding relationships/effects in their data. Consequently, a *significant* p-value would tell us to reject the null hypothesis and accept our hypothesis.\n\nLet's revisit the results from our earlier analysis where we performed a Pearson correlation to test our assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pearson correlation\nhie_2021 |>\n  select(happiness, healthy_eating) |>\n  correlation()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 |     Parameter2 |    r |        95% CI | t(305) |     p\n-------------------------------------------------------------------\nhappiness  | healthy_eating | 0.07 | [-0.04, 0.18] |   1.24 | 0.215\n\np-value adjustment method: Holm (1979)\nObservations: 307\n```\n\n\n:::\n:::\n\n\nBesides the correlation coefficient (`r`), we also find $t_{(305)} = 1.24$, which is the test statistic. The test statistic helps us determine if our data shows something unusual based on our hypothesis. A test statistic close to `0` suggests that our data is consistent with the null hypothesis, i.e. no effect/relationship. The further the test statistic moves from `0`, the more evidence we have against the null hypothesis.\n\nIn our analysis of the relationship between `happiness` and `healthy_eating`, we obtained a p-value of `0.215`. This indicates that there is a 21.5% probability of finding a t-value of `1.24` or larger if the null hypothesis is true. You probably agree that these are not good odds. Since this p-value is greater than the conventional significance level of $p \\leq 0.05$ we do not reject the null hypothesis. This means we do not have sufficient evidence to conclude that a significant relationship exists between `happiness` and `healthy_eating`.\n\nLastly, I also want to visually explain what the test statistic is and how it relates to p-values. We already learned about the normal distribution, as such, the visualisation in @fig-null-hypothesis-testing-plot will look familiar.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![t-Distribution with test statistic](10_correlations_files/figure-html/fig-null-hypothesis-testing-plot-1.png){#fig-null-hypothesis-testing-plot fig-alt='A t-distribution curve with two tails shaded in red to represent areas where p < 0.05, indicating the rejection regions. The observed t-value of 1.24 lies within the central, non-shaded area, showing it is not in the rejection region. This suggests the result is not statistically significant at the 0.05 level.' width=672}\n:::\n:::\n\n\nWhat we can see here is the distribution of test statistic scores (t-values) related to our correlation analysis. We can see that all t-values that fall within the blue area of the distribution would not count as significantly different from the null hypothesis, which means we have to accept that there is no effect/relationship to be found. However, if the t-value falls into one of the two red areas, we can reject the null hypothesis and be excited that the effect/relationship we found is *significant*.\n\nWhile we clarified how the t-value is related to the p-value, you might still be confused how these two values relate to the correlation coefficient (`r`) in our correlation results. The answer is fairly simple: we need `r` to compute our t-value. The mathematical formula is as follows:\n\n$$\nt = \\frac{r \\sqrt{n - 2}}{\\sqrt{1 - r^2}}\n$$\n\nWith this knowledge, we can reproduce $t_{(305)} = 1.24$ writing the following lines of code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the correlation coefficient and sample size\nr <- 0.07099542 # not rounded\nn <- 307\n\n# Calculate the t-value\nt_value <- (r * sqrt(n - 2)) / sqrt(1 - r^2)\nt_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.243018\n```\n\n\n:::\n:::\n\n\nWe will cover more about the `p`-value in @sec-comparing-groups and @sec-regression. For now, it is important to know that a significant correlation is one that we should look at more closely. Usually, correlations that are not significant suffer from small effect sizes. However, different samples can lead to different effect sizes and significance levels. Consider the following examples:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 | Parameter2 |    r |        95% CI | t(2) |     p\n-------------------------------------------------------------\nx          |          y | 0.77 | [-0.73, 0.99] | 1.73 | 0.225\n\np-value adjustment method: Holm (1979)\nObservations: 4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 | Parameter2 |    r |       95% CI | t(10) |       p\n---------------------------------------------------------------\nx          |          y | 0.77 | [0.36, 0.93] |  3.87 | 0.003**\n\np-value adjustment method: Holm (1979)\nObservations: 12\n```\n\n\n:::\n:::\n\n\nIn both examples $r = 0.77$, but the sample sizes are different (`4` vs `12`), and the `p`-values differ. In the first example, $p = 0.225$, which means the relationship is not significant, while in the second example, we find that $p < 0.01$ and is, therefore, highly significant. As a general rule, the bigger the sample, the more likely we find significant results, even though the effect size is small. Therefore, it is crucial to interpret correlations based on at least three factors:\n\n-   the `p`-value, i.e. significance level,\n\n-   the `r`-value, i.e. the effect size, and\n\n-   the `n`, i.e. the sample size\n\nThe interplay of all three can help determine whether a relationship is important. Therefore, when we include correlation tables in publications, we have to provide information about all three indicators.\n\nLet's put all this information into practice and investigate our third research question, which asks whether eating healthy relates to other health factors such as life expectancy, blood pressure and overweight/obesity. While we could compute three correlations independently to find an answer to our question, it is much more common to include multiple variables simultaneously and look at the results conjointly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhie_2021 |>\n  select(healthy_eating, life_expectancy, high_blood_pressure) |>\n  correlation()\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter1      |          Parameter2 |     r |         p\n---------------------------------------------------------\nhealthy_eating  |     life_expectancy |  0.70 | < .001***\nhealthy_eating  | high_blood_pressure | -0.05 | 0.395    \nlife_expectancy | high_blood_pressure | -0.08 | 0.295    \n```\n\n\n:::\n:::\n\n\nIf you have seen correlation tables before, you might find that `correlation()` does not produce the classic table by default. If you want it to look like the tables in publications, which are more compact but offer less information, you can use the function `summary()`. Which one you use is entirely up to you (or your supervisor).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhie_2021 |>\n  select(healthy_eating, life_expectancy, high_blood_pressure) |>\n  correlation() |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter       | high_blood_pressure | life_expectancy\n-------------------------------------------------------\nhealthy_eating  |               -0.05 |         0.70***\nlife_expectancy |               -0.08 |                \n\np-value adjustment method: Holm (1979)\n```\n\n\n:::\n:::\n\n\nThis table provides a clear answer to our final question. While `healthy_eating` positively relates to `life_expectancy` ($r = 0.70$, $p <0.001$) it does not correlate with `high_blood_pressure` ($r = 0.05$, $p <0.395$). In the classic correlation table, you often see `*`. These stand for the different significant levels:\n\n-   `*`, i.e. $p < 0.05$\n\n-   `**`, i.e. $p < 0.01$\n\n-   `***`, i.e. $p < 0.001$ (you might find some do not use this as a separate level)\n\nIn short, the more `*` there are attached to each value, the more significant a result. Therefore, we likely find the same relationships in newly collected data if there are many `*` and we can trust our findings.\n\n## Limitations of correlations {#sec-limitations-of-correlations}\n\nCorrelations are helpful, but only to some extend. The three most common limitations you should be aware of are:\n\n-   Correlations are not causal relationships\n\n-   Correlations can be spurious\n\n-   Correlations might only appear in sub-samples of your data\n\n### Correlations are not causal relationships {#sec-correlations-are-not-causal-relationships}\n\nCorrelations do not offer insights into causality, i.e. whether a change in one variable causes change in the other variable. Correlations only provide insights into whether these two variables tend to change when one of them changes. Still, sometimes we can infer such causality by the nature of the variables. For example, in countries with heavy rain, more umbrellas are sold. Buying more umbrellas will not cause more rain, but if there is more rain in a country, we rightly assume a higher demand for umbrellas. If we can theorise the relationship between variables, we would rather opt for a regression model instead of a correlation (see @sec-regression).\n\n### Correlations can be spurious {#sec-correlations-can-be-spurious}\n\nJust because we find a relationship between two variables does not necessarily mean that they are truly related. Instead, it might be possible that a third variable is the reason for the relationship. We call relationships between variables that are caused by a third variable *spurious correlations*. This third variable can either be part of our dataset or even something we have not measured at all. The latter case would make it impossible to investigate the relationship further. However, we can always test whether some of our variables affect the relationship between the two variables of interest. This can be done by using *partial correlations*. A *partial correlation* returns the relationship between two variables minus the relationship to a third variable. @fig-illustration-spurious-correlation depicts this visually. While `a` and `b` appear to be correlated, the correlation might only exist because they correlate with `x`. Thus, the relationship we might have computed between `a` and `b` does not actually exist and is an artefact from a relationship with a third variable. This third variable could also be one that is not part of our dataset. Consequently, we could never be sure whether the relationship between `a` and `b` is genuine.\n\n![Illustration of a spurious correlation](/images/chapter_09_img/spurious-correlation.png){#fig-illustration-spurious-correlation fig-alt=\"This figures illustrates a causal diagram with nodes (a, b, x). It shows a spurious relationship where the red circle (x) is the cause for changes in a and b. Thus, there is a dotted line between a and b as these variables are not directly related to each other.\" width=\"250\"}\n\nLet's return to our first research question. We found that `healthy_eating` is not related to `happiness`, but to `life_satisfaction`. `Life_satisfaction`, however, is related to `happiness`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correlation between variables\nhie_2021 |>\n  select(healthy_eating, happiness, life_satisfaction) |>\n  correlation()\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter1     |        Parameter2 |    r |         p\n-----------------------------------------------------\nhealthy_eating |         happiness | 0.07 | 0.215    \nhealthy_eating | life_satisfaction | 0.23 | < .001***\nhappiness      | life_satisfaction | 0.67 | < .001***\n```\n\n\n:::\n:::\n\n\nHowever, if we consider the impact of `life_satisfaction` on the relationship between `heathly_eating` and `happiness` when we compute the correlation, we retrieve a very different result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correlation between variables, considering partial correlations\nhie_2021 |>\n  select(healthy_eating, happiness, life_satisfaction) |>\n  correlation(partial = TRUE)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter1     |        Parameter2 |     r |         p\n------------------------------------------------------\nhealthy_eating |         happiness | -0.11 | 0.053    \nhealthy_eating | life_satisfaction |  0.24 | < .001***\nhappiness      | life_satisfaction |  0.67 | < .001***\n```\n\n\n:::\n:::\n\n\nSuddenly, `eating_healthy` and `happiness` show a slight negative correlation ($r = -0.11$). In other words, by controlling for the effect of `life_satisfaction` on both variables, we reversed the relationship from positive to negative. You might wonder whether this implies that eating healthily makes us less happy. If we were to take this result superficiously, it would indicate exactly this. However, as mentioned before, when we look at correlations we have to consider not only `r` but also the p-value and the sample size. While sample size seems less problematic ($n = 307$), the p-value is only $p = 0.053$, which is just shy of the required minimum significance level of `0.05`. If we strictly applied the rules, this relationship would not be classified as *significant*. Thus, the relationship would not be strong enough to derive meaningful conclusions. Even if the p-value were slightly lower, the effect size would still be very small. No matter how we crunch the numbers, healthy eating just does not make us happier.\n\n### Simpson's Paradox: When correlations betray you {#sec-simpsons-paradox}\n\nThe final limitation is so important that it even has its own name: the *Simpson's Paradox.* Let's find out what is so paradoxical about some correlations. For this demonstration, we have to make use of a different dataset: `simpson` of the `r4np` package. It contains information about changes in student `performance` and changes in `happiness`. The dataset includes responses from three different groups: `Teachers`, `Students` and `Parents`.\n\nWe would assume that an increase in students' `performance` will likely increase the `happiness` of participants. After all, all three have stakes in students' `performance`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimpson |>\n  ggplot(aes(x = performance,\n             y = happiness)) +\n  geom_point() +\n  geom_smooth(method = \"lm\",\n              formula = y ~ x,\n              se = FALSE,\n              color = \"red\")\n```\n\n::: {.cell-output-display}\n![](10_correlations_files/figure-html/simpson-paradox-plot-1.png){fig-alt='This scatter plot shows the relationship between performance and happiness, with each dot representing an individual data point. The red trend line indicates a negative correlation, suggesting that as performance increases, happiness tends to decrease slightly.' width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsimpson |>\n  select(performance, happiness) |>\n  correlation()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1  | Parameter2 |     r |         95% CI | t(298) |         p\n----------------------------------------------------------------------\nperformance |  happiness | -0.34 | [-0.44, -0.24] |  -6.32 | < .001***\n\np-value adjustment method: Holm (1979)\nObservations: 300\n```\n\n\n:::\n:::\n\n\nIt appears we were terribly wrong. It seems as if `performance` and `happiness` are moderately negatively correlated with each other. Thus, the more a student improves their `performance`, the less happy teachers, parents, and students are. I hope you agree that this is quite counter-intuitive. However, what could be the cause for such a finding?\n\nIf you have the instincts of a [true detective](https://www.imdb.com/title/tt2356777/episodes?season=1 \"True Detective\"){traget=\"blank\"}, you would think that maybe we should look at each group of participants separately. So, let's plot the same scatterplot again but colour the responses of each participant `group` differently and also compute the correlation for each subset of our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimpson |>\n  ggplot(aes(x = performance,\n             y = happiness,\n             group = group,\n             col = group)) +\n  geom_point() +\n  geom_smooth(method = \"lm\",\n              formula = y ~ x,\n              se = FALSE,\n              col = \"black\") +\n\n  # Choose custom colours for the dots\n  scale_color_manual(values = c(\"#42BDFF\", \"#FF5C67\", \"#B3AF25\"))\n```\n\n::: {.cell-output-display}\n![](10_correlations_files/figure-html/simpson-paradox-plot-groups-1.png){fig-alt='This scatter plot displays the relationship between performance and happiness across three groups: Parents (blue), Students (red), and Teachers (green). Each color-coded dot represents an individual in the respective group. The black lines represent trend lines for each group, showing a positive relationship between performance and happiness.' width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsimpson |>\n  group_by(group) |>\n  correlation()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nGroup   |  Parameter1 | Parameter2 |    r |       95% CI | t(98) |         p\n----------------------------------------------------------------------------\nParent  | performance |  happiness | 0.65 | [0.52, 0.75] |  8.47 | < .001***\nStudent | performance |  happiness | 0.65 | [0.52, 0.75] |  8.47 | < .001***\nTeacher | performance |  happiness | 0.65 | [0.52, 0.75] |  8.47 | < .001***\n\np-value adjustment method: Holm (1979)\nObservations: 100\n```\n\n\n:::\n:::\n\n\nThe results have magically been inverted. Instead of a negative correlation, we now find a strong positive correlation among all groups. This result seems to make much more sense.\n\nWhen computing correlations, we need to be aware that subsets of our data might show different directions of correlations. Sometimes insignificant correlations might suddenly become significant. This is what the *Simpson's paradox* postulates.\n\nIf your study relies solely on correlations to detect relationships between variables, which it hopefully does not, it is essential to investigate whether the detected (or undetected) correlations exist. Of course, such an investigation can only be based on the data you obtained. The rest remains pure speculation. Nevertheless, correlations are beneficial to review the bilateral relationship of your variables. It is often used as a pre-test for regressions (see @sec-regression) and similarly more advanced computations. As a technique to make inferences, correlations are a good starting point but should be complemented by other steps, if possible.\n\n## Exercises {#sec-exercises-correlations}\n\nIt is time to practice the newly acquired skills. As usual, use the code below to start the exercises for this chapter and make sure you have the `r4np` package installed before you start.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Option 1:\nlearnr::run_tutorial(\"ex_correlations\", package = \"r4np\")\n```\n:::\n",
    "supporting": [
      "10_correlations_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}